/**
 *
 * @licstart  The following is the entire license notice for the JavaScript code in this file.
 *
 * Public UI service of Identifier Services system
 *
 * Copyright (C) 2023 University Of Helsinki (The National Library Of Finland)
 *
 * This file is part of identifier-services-ui-public
 *
 * identifier-services-ui-public program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * identifier-services-ui-public is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @licend  The above is the entire license notice
 * for the JavaScript code in this file.
 *
 */

const en = {
  // Common translations - used in multiple components
  'common.isbn': 'ISBN',
  'common.ismn': 'ISMN',
  'common.isbn-ismn': 'ISBN and ISMN',
  'common.issn': 'ISSN',
  'common.user': 'User',
  'common.users': 'Users',
  'common.publisher.isbn': 'Publisher',
  'common.publishers.isbn': 'Publishers',
  'common.publisherDetails.isbn': 'Publisher details',
  'common.publisher.issn': 'Publisher',
  'common.publishers.issn': 'Publishers',
  'common.publisherDetails.issn': 'Publisher details',
  'common.request': 'Request',
  'common.requests': 'Requests',
  'common.requestDetails': 'Request details',
  'common.publication': 'Publication',
  'common.publications': 'Publications',
  'common.publicationDetails': 'Publication details',
  'common.batch': 'List of ISBNs',
  'common.batches': 'Identifier Batches',
  'common.batchDetails': 'Identifier list details',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.true': 'Yes',
  'common.true.allLangs': 'Kyllä / Ja / Yes',
  'common.false': 'No',
  'common.false.allLangs': 'Ei / Nej / No',
  'common.noData': 'No search results',
  'common.blank': 'Blank',
  'common.search.inputPlaceholder': 'Search...',
  'common.search.searchById': 'Search by ID...',
  'common.search.searchByPublisherName': 'Search by publisher name or email...',
  'common.noValue': '-',
  'common.name': 'Name',
  'common.undefined': 'Not defined',
  'common.link': 'Link',
  'common.identifier': 'Identifier',
  'common.identifiers': 'Identifiers',
  'common.identifiersPrinted': 'Identifiers (printed)',
  'common.identifiersElectronical': 'Identifiers (electronical)',
  'common.amount': 'Amount',
  'common.status': 'Status',
  'common.id': 'ID',
  'common.contactDetails': 'Contact details',
  'common.noLink': 'Not generated',
  'common.important.info': 'Important information',
  'common.datePicker.helperText': 'E.g. 06/2023',
  'common.privacypolicy.title': 'Privacy Policy',
  'common.other': 'other',
  'common.errorPage': 'Error page',
  'common.skipLink': 'Skip to main content',
  'common.inLibrary': 'In National Library',
  'common.free': 'free of charge',
  // Numbers
  'common.one': 'One',
  'common.two': 'Two',
  'common.three': 'Three',
  'common.four': 'Four',
  // Publication languages
  'common.fin': 'Finnish',
  'common.swe': 'Swedish',
  'common.eng': 'English',
  'common.smi': 'Sami',
  'common.fre': 'French',
  'common.ger': 'German',
  'common.rus': 'Russian',
  'common.spa': 'Spanish',
  'common.mul': 'Other/bilingual',
  // Publisher's preferred languages
  'common.fi-FI': 'Finnish',
  'common.en-GB': 'English',
  'common.sv-SE': 'Swedish',
  // ISBN/ISMN publication types
  'common.BOOK': 'Book/booklet',
  'common.DISSERTATION': 'Dissertation',
  'common.MUSIC': 'Sheet music',
  'common.SHEET_MUSIC': 'Sheet music',
  'common.MAP': 'Map',
  'common.OTHER': 'Other',
  // ISSN publication types
  'common.journal': 'Journal',
  'common.newsletter': 'Newsletter',
  'common.staff_magazine': 'Staff magazine',
  'common.membership_based_magazine': 'Membership-based magazine',
  'common.newspaper': 'Newspaper',
  'common.free_paper': 'Free paper',
  'common.monography_series': 'Monograph series',
  'common.cartoon': 'Cartoon',
  'common.other_serial': 'Other (e.g. statistics, yearbook, report)',
  // ISSN publication frequency options
  'common.a': 'Yearly',
  'common.f': 'Bi-yearly',
  'common.q': 'Quarterly',
  'common.b': 'Bi-monthly',
  'common.m': 'Monthly',
  'common.w': 'Weekly',
  'common.d': 'Daily',
  'common.k': 'Continuously',
  'common.#': 'Irregular',
  'common.z': 'Other',
  // ISSN publication medium
  'common.printed': 'printed',
  'common.online': 'electronical',
  'common.cdrom': 'CD-ROM',
  // Months
  'common.month.1': 'January',
  'common.month.2': 'February',
  'common.month.3': 'March',
  'common.month.4': 'April',
  'common.month.5': 'May',
  'common.month.6': 'June',
  'common.month.7': 'July',
  'common.month.8': 'August',
  'common.month.9': 'September',
  'common.month.10': 'October',
  'common.month.11': 'November',
  'common.month.12': 'December',

  // Home page
  'homePage.title': 'Identifier Services',
  'homePage.description.part1': 'International standard identifiers (ISBN, ISSN and ISMN) uniquely identify publications. Identifiers are used, for example, in publishing industry\'s ordering and distribution systems.',
  'homePage.description.part2': 'ISBN identifies books, ISMN notated music publications and ISSN serial publications.',
  'homePage.description.part3': 'In Finland, these identifiers are applied for from the Finnish ISBN and ISSN Agencies operating at the National Library of Finland. The identifiers are free of charge.',
  'homePage.link': 'More about {link}',
  'homePage.instructions.title': 'Instructions for completing the forms',
  'homePage.instructions.main.text': 'If you publish regularly (for example, one or more publications a year) and you are not yet a member of the ISBN/ISMN system, please complete both the electronic publisher registration form (ISBN/ISMN) and the ISBN/ISMN application form.{lineBreak}{lineBreak}If your publishing activities are occasional or you have already joined the ISBN/ISMN system, please complete the ISBN/ISMN application for books and sheet music only.{lineBreak}{lineBreak}Information on publishers entered in the ISBN/ISMN system is published in the international databases Global Register of Publishers and/or Music Publishers\' International ISMN Database. This information is also used by the Finnish ISBN Agency and published on its website.',
  'homePage.instructions.isbn-ismn.text': 'An ISBN identifies books and an ISMN identifies notated music publications intended for public use. The Finnish national ISBN Agency is responsible for handing out ISBNs and ISMNs in Finland. The Agency maintains a national publisher register and provides information about Finnish publishers for national and international use.{lineBreak}{lineBreak}Identifiers as a part of metadata serve the publishing industry and the library sector in their entirety, supporting identification, processing and availability of publications. Identifiers are used, for example, in publishing industry\'s ordering and distribution systems to speed up the identification of publications - as well as in international and domestic joint catalogues, bibliographies, library lending systems and information retrieval.{lineBreak}{lineBreak}Each book or sheet music publication, each different publication form (printed, audio-visual, digital) and each edition containing changes are issued a separate ISBN or ISMN. This promotes identification of publications in the publishing industry\'s distribution chain and ensures that customers get the desired publication at their disposal. Publication format may be a printed book or an audio-visual or electronic recording.',
  'homePage.instructions.issn.text': 'An ISSN identifies continuously published publications, such as journals and series. The Finnish national ISSN Agency is responsible for providing the identifiers in Finland and sends the information about publications that have received an ISSN to the {link} database.{lineBreak}{lineBreak}Identifiers as a part of metadata serve the publishing industry and the library sector in their entirety, supporting identification, processing and availability of publications.{lineBreak}{lineBreak}Identifiers are used, for example, in publishing industry\'s ordering and distribution systems to speed up the identification of publications as well as in international and domestic joint catalogues, bibliographies, library lending systems and information retrieval. An ISSN is inseparable from the title of the publication; if the title of the publication changes, the identifier must also be changed. A separate ISSN is given to different forms of publication.',

  // Menu bar
  'menu.mobile': 'Menu',
  'menu.home': 'Home',
  'menu.publisherRegistry': 'Publisher Register',
  'menu.forms': 'Forms',
  'menu.forms.publisherRegistration': 'Publisher registration form',
  'menu.forms.publicationRegistration': 'ISBN-/ISMN-forms',
  'menu.forms.issnPublicationRegistration': 'ISSN-form',
  'menu.forms.publicationRegistration.isbn-ismn': 'ISBN/ISMN application for books and sheet music',
  'menu.forms.publicationRegistration.issn': 'ISSN application for periodicals',
  'menu.forms.contactInformationChange': 'Change contact information (ISBN/ISMN)',

  // Footer
  'footer.privacyPolicy': 'Privacy policy',
  'footer.library': 'The National Library of Finland',
  'footer.address': 'PL 15 (Unioninkatu 36)',
  'footer.zip': '00014 University of Helsinki',
  'footer.contact': 'Contacts',
  'footer.copyright': '© The National Library of Finland 2023',
  'footer.socials': 'Follow on social media',

  // Alt texts (Kuvatekstit)
  'altText.logo.library': 'The official logo of The National Library of Finland',

  // Ranges (Tunnistelohkot)
  'ranges.identifierType': 'Type',

  // Error messages
  'error.field.required': 'Required',
  'error.format.issn': 'Invalid ISSN-identifier',
  'error.format.phone': 'Invalid phone number',
  'error.format.city': 'Invalid city',
  'error.format.publishingActivityAmount': 'Max. 5 characters',
  'error.format.copies': 'Max. 10 characters',
  'error.format.maxLength': 'Given value is too long',
  'error.format.minLength': 'Given value is too short',
  'error.format.integer': 'Given value must be a number',
  'error.format.integer.twoDigits': 'Given value must be a number with two digits (e.g. 39)',
  'error.format.year': 'Invalid year',
  'error.format.email': 'Invalid email address',
  'error.format.www': 'Invalid URL, please use http:// or https://',
  'error.format.edition': 'Max 2 characters',
  'error.postalAddress.zip.format': 'Invalid postal code',
  'error.postalAddress.city.format': 'Invalid city',
  'error.publicationRegistrationIsbnIsmn.form.availability': 'ISBN identifiers are only granted for publications intended for public use',
  'error.publicationRegistrationIsbnIsmn.form.otherUniversitites': 'ISBN Agency grants ISBN identifiers only for dissertations made at the University of Helsinki',
  'error.date.invalid': 'Invalid date',
  'error.date.min': 'The date to be entered must be after current date',
  'error.identifierBatch.invalid': 'Loading of identifier batch failed. Please try again or contact customer service',
  'error.formEdit': 'There are errors in the form, please check the fields marked in red: ',
  'error.emptyField': ' ',
  'error.classification.maxAmount': 'You can add max. 5 classification keywords',

  // Error page texts
  'errorPage.header': 'Sorry, something went wrong',
  'errorPage.message.serviceDown': 'The service is down. Please try again later. If the problem persists, please contact customer service',
  'errorPage.message.serviceUnderMaintenance': 'The service is under maintenance. Please try again later. If the problem persists, please contact customer service',
  'errorPage.message.defaultError': 'Unknown error. Please try again or contact customer service',
  'errorPage.message.generatingMessageFailed': 'Operation failed, please try again or contact customer service',
  'errorPage.publicationRequestError': 'The page could not be loaded. Please check the address and try again. If the problem persists, please contact customer service',
  'errorPage.accessdenied.heading': 'Access denied',
  'errorPage.accessdenied.message': 'You do not have permission to access this page',
  'errorPage.admin.genericError': 'System error. Please contact system administrator for assistance',

  // Common form translations - used in multiple forms
  'form.common.name': 'Publisher name',
  'form.common.otherNames': 'Other names',
  'form.common.previousNames': 'Previous names',
  'form.common.phone': 'Phone number',
  'form.common.email': 'Email',
  'form.common.contactPerson': 'Contact person',
  'form.common.website': 'Website',
  'form.common.address': 'Address',
  'form.common.addressLine1': 'Address 2',
  'form.common.zip': 'Postal code',
  'form.common.city': 'City',
  'form.common.affiliates': 'Affiliates',
  'form.common.affiliateOf': 'Affiliate of',
  'form.common.distributors': 'Distributors',
  'form.common.distributorOf': 'Distributor of',
  'form.common.currentYear': 'Estimated publication amount (this year)',
  'form.common.nextYear': 'Estimated publication amount (next year)',
  'form.common.classification': 'Classification',
  'form.common.classificationKeywords': 'Keywords',
  'form.common.classificationOther': 'Other classification',
  'form.common.classificationCodes': 'Classification codes',
  'form.common.publisherIdentifier': 'Publisher identifier',
  'form.common.publisherIdentifiers': 'Publisher identifiers',
  'form.common.title': 'Title',
  'form.common.subtitle': 'Subtitle',
  'form.common.authorName': 'Author name',
  'form.common.selectFormat': 'Select format',
  'form.common.publicationMonth': 'Publication month',
  'form.common.publicationYear': 'Publication year',
  'form.common.language': 'Language',
  'form.common.identifier': 'Identifier',
  'form.common.volume': 'Volume',
  'form.common.type': 'Type of publication',
  'form.common.publishingActivities': 'Publishing activities',
  'form.common.instruction.multipleSelect': 'Select one or more options from the list',
  'form.common.instruction.createableSelect': 'To add a new option, type the name of the option and press Enter',
  'form.common.basicInfo': 'Basic information',
  'form.common.postalAddress': 'Postal address',
  'form.common.activeIdentifier': 'Active {type}-identifier',
  'form.common.organizationDetails': 'Organisation details',
  'form.common.frequency': 'Publication frequency',
  'form.common.activity': 'Publishing activity',
  'form.common.additionalDetails': 'Additional details',
  'form.common.noAdditionalDetails': 'No additional details',
  'form.common.createdAndUpdated': 'Created and updated',
  'form.common.created': 'Created',
  'form.common.createdBy': 'Created by',
  'form.common.modified': 'Modified',
  'form.common.modifiedBy': 'Modified by',
  'form.common.printFormat': 'Print format',
  'form.common.fileFormat': 'File format',
  'form.common.subRangeType': 'Type of publisher identifier',
  'form.common.otherInfo': 'Other information',
  'form.common.format': 'Format',
  'form.common.publicationCity': 'Place of publication',
  'form.common.updated': 'Updated',
  'form.common.confirmation': 'Confirmation (old system)',
  'form.common.scale': 'Scale',
  'form.common.archiveRecord': 'Archive record',
  'form.common.url': 'Web address',

  // Form edition translations (Painos)
  'form.edition.first': 'First',
  'form.edition.second': 'Second',
  'form.edition.third': 'Third',
  'form.edition.fourth': 'Fourth',
  'form.edition.fifth': 'Fifth',
  'form.edition.sixth': 'Sixth',
  'form.edition.seventh': 'Seventh',
  'form.edition.eighth': 'Eighth',
  'form.edition.ninth': 'Ninth',
  'form.edition.tenth': 'Tenth',
  'form.edition.eleventh': 'Eleventh',
  'form.edition.twelfth': 'Twelfth',
  'form.edition.thirteenth': 'Thirteenth',
  'form.edition.fourteenth': 'Fourteenth',
  'form.edition.fifteenth': 'Fifteenth',

  // Printed publication format (Kansityyppi)
  'form.printFormat.paperback': 'Paperback',
  'form.printFormat.hardback': 'Hardback',
  'form.printFormat.spiral_binding': 'Spiral binding',
  'form.printFormat.other_print': 'Other (printed)',

  // File format (Tiedostomuoto)
  'form.fileFormat.pdf': 'PDF',
  'form.fileFormat.epub': 'EPUB',
  'form.fileFormat.cd_rom': 'CD-ROM',
  'form.fileFormat.mp3': 'MP3',
  'form.fileFormat.other': 'Other (electronical)',

  // Frequency (Julkaisutiheys)
  'form.frequency.yearly': 'Yearly',
  'form.frequency.monthly': 'Monthly',
  'form.frequency.weekly': 'Weekly',
  'form.frequency.daily': 'Daily',
  'form.frequency.biyearly': 'Bi-yearly',
  'form.frequency.quarterly': 'Quarterly',
  'form.frequency.bimonthly': 'Bi-monthly',
  'form.frequency.irregular': 'Irregular',
  'form.frequency.continuously': 'Continuously',
  'form.frequency.other': 'Other',

  // Button labels
  'form.button.label.back': 'Back',
  'form.button.label.next': 'Next',
  'form.button.label.submit': 'Submit',
  'form.button.label.proceed': 'Continue',
  'form.button.label.add': 'Add',
  'form.button.label.addPublication': 'Add publication',
  'form.button.label.delete': 'Delete',
  'form.button.label.downloadAsTextfile': 'Download as text file',
  'form.button.label.showIdentifiers': 'Show Identifiers',

  // Publisher registration form (Kustantajan liittymislomake)
  'form.publisherRegistration.instructions.title': 'When joining the ISBN system, the publisher commits to the following obligations: ',
  'form.publisherRegistration.instructions.note0': 'An ISBN must appear on all the publications published.',
  'form.publisherRegistration.instructions.note1.part1': 'The ISBN should be printed as advised on the ',
  'form.publisherRegistration.instructions.note1.link': 'ISBN Agency\'s website',
  'form.publisherRegistration.instructions.note1.part2': '.',
  'form.publisherRegistration.instructions.note2': 'The publisher keeps a list of its publications sorted according to their ISBN numbers.',
  'form.publisherRegistration.instructions.note3': 'The publisher will send a copy of each publication to the Finnish ISBN Agency immediately after publication.',
  'form.publisherRegistration.instructions.note4': 'Entered publisher information is published in the international databases Global Register of Publishers and/or Music Publishers\' International ISMN Database. The information is also used by the Finnish ISBN Agency and published on its website.',
  'form.publisherRegistration.title': 'Publisher registration',
  'form.publisherRegistration.stepper.label.basicInformation': 'Basic information',
  'form.publisherRegistration.stepper.label.publishingActivities': 'Publishing activities',
  'form.publisherRegistration.stepper.label.organizationDetails': 'Organisation details',
  'form.publisherRegistration.stepper.label.preview': 'Preview',
  'form.publisherRegistration.basicInformation.name': 'Publisher name*',
  'form.publisherRegistration.basicInformation.address': 'Postal address*',
  'form.publisherRegistration.basicInformation.city': 'City*',
  'form.publisherRegistration.basicInformation.zip': 'Postal code*',
  'form.publisherRegistration.basicInformation.phone': 'Phone number*',
  'form.publisherRegistration.basicInformation.publisherEmail': 'Email*',
  'form.publisherRegistration.basicInformation.website': 'Website',
  'form.publisherRegistration.basicInformation.contactPerson': 'Contact person*',
  'form.publisherRegistration.basicInformation.email': 'Email*',
  'form.publisherRegistration.basicInformation.otherNames': 'Other name forms',
  'form.publisherRegistration.publishingActivities.currentYear': 'Please estimate the number of publications you publish this year*',
  'form.publisherRegistration.publishingActivities.nextYear': 'Please estimate the number of publications you publish next year*',
  'form.publisherRegistration.publishingActivities.classification': 'Classification codes*',
  'form.publisherRegistration.publishingActivities.classification.placeholder': 'Add classification keyword*',
  'form.publisherRegistration.publishingActivities.classificationOther': 'Other keywords',
  'form.publisherRegistration.organization.affiliates': 'Affiliates',
  'form.publisherRegistration.organization.affiliateOf': 'Affiliate of',
  'form.publisherRegistration.organization.distributors': 'Distributors',
  'form.publisherRegistration.organization.distributorOf': 'Distributor of',
  'form.publisherRegistration.classification.general': 'General',
  'form.publisherRegistration.classification.book-business-lib': 'Book business, Libraries',
  'form.publisherRegistration.classification.text-books': 'Text books',
  'form.publisherRegistration.classification.children-book': 'Children\'s books',
  'form.publisherRegistration.classification.official-publication': 'Official publications',
  'form.publisherRegistration.classification.university-publication': 'University publications',
  'form.publisherRegistration.classification.electronic-publication': 'Electronic publications',
  'form.publisherRegistration.classification.audiovisual': 'Audiovisual material. Videos',
  'form.publisherRegistration.classification.philosophy': 'Philosophy',
  'form.publisherRegistration.classification.psychology': 'Psychology',
  'form.publisherRegistration.classification.paranormal': 'Paranormal phenomena, Occultism, Astrology',
  'form.publisherRegistration.classification.religion': 'Religion, Theology',
  'form.publisherRegistration.classification.christianity': 'Christianity',
  'form.publisherRegistration.classification.orthodox': 'The Ortodox Church',
  'form.publisherRegistration.classification.other-religions': 'Other religions',
  'form.publisherRegistration.classification.social-science': 'Social Science, Sociology',
  'form.publisherRegistration.classification.political-studies': 'Political Studies, International Politics',
  'form.publisherRegistration.classification.military': 'Military Science',
  'form.publisherRegistration.classification.sociology': 'Sociology',
  'form.publisherRegistration.classification.economics': 'Economics',
  'form.publisherRegistration.classification.law': 'Law',
  'form.publisherRegistration.classification.public-administration': 'Public administration',
  'form.publisherRegistration.classification.education': 'Education',
  'form.publisherRegistration.classification.ethnography': 'Ethnography, Folklore',
  'form.publisherRegistration.classification.local-history': 'Local history research',
  'form.publisherRegistration.classification.social-politics': 'Social Politics, Welfare',
  'form.publisherRegistration.classification.mass-media': 'Mass Media',
  'form.publisherRegistration.classification.literature': 'Literature',
  'form.publisherRegistration.classification.fiction': 'Fiction',
  'form.publisherRegistration.classification.poetry': 'Poetry',
  'form.publisherRegistration.classification.cartoons': 'Cartoons',
  'form.publisherRegistration.classification.science-fiction': 'Science Fiction',
  'form.publisherRegistration.classification.crime-fiction': 'Crime Fiction',
  'form.publisherRegistration.classification.linguistic': 'Linguistic',
  'form.publisherRegistration.classification.sexual-minorities': 'Sexual Minorities',
  'form.publisherRegistration.classification.minorities': 'Minorities',
  'form.publisherRegistration.classification.science': 'Science',
  'form.publisherRegistration.classification.mathematics': 'Mathematics, Statistics',
  'form.publisherRegistration.classification.astronomy': 'Astronomy',
  'form.publisherRegistration.classification.physics': 'Physics',
  'form.publisherRegistration.classification.chemistry': 'Chemistry',
  'form.publisherRegistration.classification.geology': 'Geology',
  'form.publisherRegistration.classification.biology': 'Biology',
  'form.publisherRegistration.classification.zoology': 'Zoology',
  'form.publisherRegistration.classification.botany': 'Botany',
  'form.publisherRegistration.classification.environmental-studies': 'Environmental Studies, Conservation',
  'form.publisherRegistration.classification.technology': 'Technology',
  'form.publisherRegistration.classification.engineering': 'Engineering Technology',
  'form.publisherRegistration.classification.industry': 'Industry',
  'form.publisherRegistration.classification.construction': 'Construction',
  'form.publisherRegistration.classification.transport': 'Transport, Post',
  'form.publisherRegistration.classification.information-tech': 'Information Technology',
  'form.publisherRegistration.classification.medicine': 'Medicine, Psychiatry',
  'form.publisherRegistration.classification.odontology': 'Odontology',
  'form.publisherRegistration.classification.veteriniry': 'Veterinary Medicine',
  'form.publisherRegistration.classification.pharmacology': 'Pharmacology, Homeopathy',
  'form.publisherRegistration.classification.forestry': 'Forestry',
  'form.publisherRegistration.classification.agriculture': 'Agriculture',
  'form.publisherRegistration.classification.handicraft': 'Handicraft',
  'form.publisherRegistration.classification.art': 'Art',
  'form.publisherRegistration.classification.performing-art': 'Performing Art',
  'form.publisherRegistration.classification.theatre': 'Theatre, Film',
  'form.publisherRegistration.classification.dance': 'Dance',
  'form.publisherRegistration.classification.visual-art': 'Visual Arts',
  'form.publisherRegistration.classification.art-history': 'Art History',
  'form.publisherRegistration.classification.architecture': 'Architecture, Industrial Art',
  'form.publisherRegistration.classification.fashion': 'Fashion',
  'form.publisherRegistration.classification.music': 'Music',
  'form.publisherRegistration.classification.antique': 'Antiques, Collecting',
  'form.publisherRegistration.classification.city-regional': 'City and Regional Planning',
  'form.publisherRegistration.classification.leisure-hobbies': 'Leisure and Hobbies',
  'form.publisherRegistration.classification.sports': 'Sports',
  'form.publisherRegistration.classification.games': 'Games',
  'form.publisherRegistration.classification.hunting-fishing': 'Hunting and Fishing',
  'form.publisherRegistration.classification.gardening': 'Gardening',
  'form.publisherRegistration.classification.home-economic': 'Home Economics',
  'form.publisherRegistration.classification.health-beauty': 'Health and Beauty',
  'form.publisherRegistration.classification.photography': 'Photography',
  'form.publisherRegistration.classification.tourism': 'Tourism, Travel',
  'form.publisherRegistration.classification.humour': 'Humour',
  'form.publisherRegistration.classification.history': 'History',
  'form.publisherRegistration.classification.geography': 'Geography',
  'form.publisherRegistration.classification.map-atlases': 'Maps and Atlases',
  'form.publisherRegistration.classification.archeology': 'Archeology',
  'form.publisherRegistration.classification.genealogy': 'Genealogy',
  'form.publisherRegistration.classification.numismatics': 'Numismatics',
  'form.publisherRegistration.preview.publishingFrequency': 'Publishing frequency',
  'form.publisherRegistration.preview.organizationDetails': 'Organisation details',
  'form.publisherRegistration.preview.postalAddress': 'Postal address',
  'form.publisherRegistration.preview.publisherInformation': 'Publisher information',
  'form.publisherRegistration.card.affiliates': 'Do you have any affiliated companies in Finland or abroad? Please provide the names and addresses of the companies and an estimate of the annual publication amounts.',
  'form.publisherRegistration.card.distributors': 'Do you have any foreign or Finnish distributors? Please provide the names and addresses of the companies.',

  // ISBN/ISMN-form
  'form.isbnIsmn.title': 'Apply for ISBN or ISMN identifier',
  'form.isbnIsmn.stepper.label.availabilityInformation': 'Basic information',
  'form.isbnIsmn.stepper.label.publisherBasicInfo': 'Publisher',
  'form.isbnIsmn.stepper.label.publishingActivities': 'Publishing activities',
  'form.isbnIsmn.stepper.label.basicInformation': 'Publication',
  'form.isbnIsmn.stepper.label.authorInformation': 'Authors',
  'form.isbnIsmn.stepper.label.seriesInformation': 'Series',
  'form.isbnIsmn.stepper.label.formatBasic': 'Publication format',
  'form.isbnIsmn.stepper.label.additionalDetails': 'Additional details',
  'form.isbnIsmn.stepper.label.dissertationFormat': 'Dissertation format',
  'form.isbnIsmn.stepper.label.contactInfo': 'Contacts',
  'form.isbnIsmn.stepper.label.universityInformation': 'University information',
  'form.isbnIsmn.stepper.label.preview': 'Preview',
  'form.isbnIsmn.availability.publicationsPublic': 'Is your publication intended for public use (e.g., for library use or sale in bookshops) or will it be made otherwise available to the public? If your publication is a web-version or an ebook, will it be free to download or to buy?*',
  'form.isbnIsmn.availability.type': 'Publication is*',
  'form.isbnIsmn.availability.type.option.book': 'Book/booklet',
  'form.isbnIsmn.availability.type.option.dissertation': 'Dissertation',
  'form.isbnIsmn.availability.type.option.sheet_music': 'Sheet music',
  'form.isbnIsmn.availability.type.option.map': 'Map',
  'form.isbnIsmn.availability.type.option.other': 'Other',
  'form.isbnIsmn.availability.publicationsPublic.label': 'Is your publication intended for public use?',
  'form.isbnIsmn.availability.type.label': 'Publication is',
  'form.isbnIsmn.publisherInfo.name': 'Publisher name*',
  'form.isbnIsmn.publisherInfo.publisherIdentifierStr': 'Publisher identifier',
  'form.isbnIsmn.publisherInfo.address': 'Address*',
  'form.isbnIsmn.publisherInfo.zip': 'Postal code*',
  'form.isbnIsmn.publisherInfo.city': 'City*',
  'form.isbnIsmn.publisherInfo.phone': 'Phone number*',
  'form.isbnIsmn.publisherInfo.contactPerson': 'Contact person*',
  'form.isbnIsmn.publisherInfo.email': 'Email*',
  'form.isbnIsmn.publishingActivities.hasPublishedBefore': 'Have you published previously?',
  'form.isbnIsmn.publishingActivities.occasionalOrContinuous': 'Are your publishing activities occasional/continuous?*',
  'form.isbnIsmn.publishingActivities.thisYear': 'How many publications do you publish annually?',
  'form.isbnIsmn.publishingActivities.option.occasional': 'Occasional',
  'form.isbnIsmn.publishingActivities.option.continuous': 'Continuous',
  'form.isbnIsmn.university.isHelsinki': 'Is the dissertation made at the University of Helsinki?',
  'form.isbnIsmn.university.contactInfo.contactPerson': 'Contact person*',
  'form.isbnIsmn.university.contactInfo.address': 'Address*',
  'form.isbnIsmn.university.contactInfo.zip': 'Postal code*',
  'form.isbnIsmn.university.contactInfo.city': 'City*',
  'form.isbnIsmn.university.contactInfo.phone': 'Phone number*',
  'form.isbnIsmn.university.contactInfo.email': 'Email*',
  'form.isbnIsmn.publicationInfo.title': 'Title*',
  'form.isbnIsmn.publicationInfo.subtitle': 'Subtitle',
  'form.isbnIsmn.publicationInfo.language': 'Language*',
  'form.isbnIsmn.publicationInfo.scale': 'Scale',
  'form.isbnIsmn.publicationInfo.publicationMonth': 'Month of publication*',
  'form.isbnIsmn.publicationInfo.publicationYear': 'Year of publication*',
  'form.isbnIsmn.authors.givenName': 'Authors first name*',
  'form.isbnIsmn.authors.familyName': 'Authors last name*',
  'form.isbnIsmn.authors.role': 'Role*',
  'form.isbnIsmn.authors.role.option.author': 'Author',
  'form.isbnIsmn.authors.role.option.illustrator': 'Illustrator',
  'form.isbnIsmn.authors.role.option.translator': 'Translator',
  'form.isbnIsmn.authors.role.option.editor': 'Editor',
  'form.isbnIsmn.authors.card.name': 'Name:',
  'form.isbnIsmn.authors.card.roles': 'Roles:',
  'form.isbnIsmn.authors.card.noAuthors': 'Add author by filling the information and press the \'Add\' button',
  'form.isbnIsmn.authors.card.addMoreAuthors': 'Add more authors by filling the information and press the \'Add\' button. Max. 4 authors are allowed. Other authors will be considered when the publications arrives to the National Library.',
  'form.isbnIsmn.authors.card.maxAuthors': 'You have added maximum amount of authors. Other authors will be considered when the publications arrives to the National Library.',
  'form.isbnIsmn.series.title': 'Series title',
  'form.isbnIsmn.series.volume': 'Volume number',
  'form.isbnIsmn.format.label': 'Publication format*',
  'form.isbnIsmn.format.option.print': 'Printed',
  'form.isbnIsmn.format.option.electronical': 'Electronical',
  'form.isbnIsmn.format.option.print_electronical': 'Both printed and electronical',
  'form.isbnIsmn.format.dissertation.option.printed': 'Printed (paperback)',
  'form.isbnIsmn.format.dissertation.option.electronic': 'Electronical (PDF)',
  'form.isbnIsmn.format.dissertation.option.both': 'Both printed (paperback) and electronical (PDF)',
  'form.isbnIsmn.format.dissertation.option.printed.edition': 'Edition',
  'form.isbnIsmn.format.dissertation.option.printed.manufacturer': 'Manufacturer',
  'form.isbnIsmn.format.dissertation.option.printed.city': 'City',
  'form.isbnIsmn.format.printFormat': 'Cover format*',
  'form.isbnIsmn.format.printFormat.other': 'Other cover format*',
  'form.isbnIsmn.format.printFormat.printed.manufacturer': 'Manufacturer',
  'form.isbnIsmn.format.printFormat.printed.city': 'City',
  'form.isbnIsmn.format.printFormat.printed.edition': 'Edition',
  'form.isbnIsmn.format.printFormat.printed.copies': 'Copies',
  'form.isbnIsmn.format.fileFormat': 'File format*',
  'form.isbnIsmn.format.fileFormat.other': 'Other file format*',
  'form.isbnIsmn.additionalDetails': 'Additional details',
  'form.isbnIsmn.preview.publisherDetails': 'Publisher details',
  'form.isbnIsmn.preview.publicationInfo': 'Publication details',
  'form.isbnIsmn.preview.universityName': 'University',
  'form.isbnIsmn.preview.helsinki': 'University of Helsinki',
  'form.isbnIsmn.preview.previouslyPublished': 'Has published previously',
  'form.isbnIsmn.preview.thisYear': 'Estimated number of publications this year',
  'form.isbnIsmn.preview.format': 'Format',
  'form.isbnIsmn.preview.formatDetails': 'Publication format',
  'form.isbnIsmn.preview.printFormat': 'Cover format',
  'form.isbnIsmn.preview.printFormatOther': 'Other cover format',
  'form.isbnIsmn.preview.fileFormat': 'File format',
  'form.isbnIsmn.preview.fileformatOther': 'Other file format',
  'form.isbnIsmn.preview.authors': 'Authors',
  'form.isbnIsmn.preview.additionalDetails': 'Additional details',
  'form.isbnIsmn.preview.manufacturer': 'Manufacturer',
  'form.isbnIsmn.preview.city': 'City',
  'form.isbnIsmn.preview.edition': 'Edition',
  'form.isbnIsmn.preview.run': 'Copies',
  'form.isbnIsmn.preview.seriesDetails': 'Series details',
  'form.isbnIsmn.preview.publicationDetails': 'Basic information',
  'form.isbnIsmn.preview.isPublic': 'Public',
  'form.isbnIsmn.card.universityOfHelsinki': 'Before you fill in this ISBN application form, please check at your department/faculty if you get an ISBN from your university. If needed, please contact ISBN Agency.',
  'form.isbnIsmn.card.otherUniversity': 'Before you fill in this ISBN application form, please check at your department/faculty if you get an ISBN from there. If needed, please contact ISBN Agency for more information.',
  'form.isbnIsmn.card.publicationIsPublic': 'If your publication is intended for private use only (e.g., for friends, family or the internal use of an association or organisation), publication will not be assigned an ISBN.',
  'form.isbnIsmn.card.editionInfo': 'Information about new editions',
  'form.isbnIsmn.card.publicationInfo': 'An ISBN cannot be requested after the book is printed, or published online.',
  'form.isbnIsmn.card.seriesInfo': 'Enter series details if the publication is part of a series.',

  // ISSN-form
  'form.issn.title': 'ISSN request form',
  'form.issn.stepper.label.publisherInformation': 'Publisher information',
  'form.issn.stepper.label.publicationInformation_1': '1. Publication information',
  'form.issn.stepper.label.publicationInformation_2': '2. Publication information',
  'form.issn.stepper.label.publicationInformation_3': '3. Publication information',
  'form.issn.stepper.label.publicationInformation_4': '4. Publication information',
  'form.issn.stepper.label.publicationVersions': 'Amount of publication versions',
  'form.issn.stepper.label.publicationVersionsCheck': 'Other versions (check)',
  'form.issn.stepper.label.preview': 'Preview',
  'form.issn.versionInfo.number_of_versions': 'Amount of publication versions',
  'form.issn.publisherInfo.name': 'Publisher name*',
  'form.issn.publisherInfo.contact_person': 'Contact person*',
  'form.issn.publisherInfo.email': 'Email*',
  'form.issn.publisherInfo.phone': 'Phone number*',
  'form.issn.publisherInfo.address': 'Address*',
  'form.issn.publisherInfo.zip': 'Postal code*',
  'form.issn.publisherInfo.city': 'City*',
  'form.issn.publicationInfo.title': 'Title*',
  'form.issn.publicationInfo.title.instructions': 'ISSN is linked to the title of the publication. The title must be permanent and it must be printed in the publication.',
  'form.issn.publicationInfo.subtitle': 'Subtitle',
  'form.issn.publicationInfo.place_of_publication': 'Place of publication*',
  'form.issn.publicationInfo.printer': 'Printing house',
  'form.issn.publicationInfo.issued_from_year': 'Issued under this title (since year)*',
  'form.issn.publicationInfo.issued_from_number': 'From number*',
  'form.issn.publicationInfo.frequency': 'Publishing frequency*',
  'form.issn.publicationInfo.language': 'Language*',
  'form.issn.publicationInfo.publication_type': 'Publication type*',
  'form.issn.publicationInfo.other': 'other, which*',
  'form.issn.publicationInfo.medium': 'Publication form/Medium*',
  'form.issn.publicationInfo.url': 'If the publication is issued online, provide web-address*',
  'form.issn.publicationInfo.previous': 'Previous title*',
  'form.issn.publicationInfo.issn': 'Previous ISSN',
  'form.issn.publicationInfo.last_issue': 'The last issue under this title was (issue/year)*',
  'form.issn.publicationInfo.main_series': 'Title of the main series*',
  'form.issn.publicationInfo.main_series_issn': 'ISSN of the main series',
  'form.issn.publicationInfo.subseries': 'Title of the subseries*',
  'form.issn.publicationInfo.subseries_issn': 'ISSN of the subseries',
  'form.issn.publicationInfo.another_medium': 'Title of another medium*',
  'form.issn.publicationInfo.another_medium_issn': 'ISSN of another medium',
  'form.issn.publicationInfo.additional_info': 'Additional details',
  'form.issn.publicationInfo.publication_was_issued': 'Is there a previous title for the publication? ',
  'form.issn.publicationInfo.publication_has_main_series': 'Is the publication part of the main series?',
  'form.issn.publicationInfo.publication_has_subseries': 'Does the publication have subseries?',
  'form.issn.publicationInfo.publication_has_another_medium': 'Has the publication already been published in another form/medium?',
  'form.issn.publicationInfo.publication_has_another_medium.instructions': 'If the same publication was issued in another form/medium, add its information here.',
  'form.issn.publicationInfo.instructions.part1': 'Publication in several media',
  'form.issn.publicationInfo.instructions.part2': 'If the same publication is regularly issued in another form/medium (print, online), it will need its own ISSN. Enter details on each form/medium separately by choosing the correct amount of publication versions.',
  'form.issn.publicationInfo.instructions.part3': 'Publication in several languages',
  'form.issn.publicationInfo.instructions.part4': 'If the same publication is issued in several languages, language version needs an ISSN of its own. Enter details on each language version separately by choosing the correct amount of publication versions.',
  'form.issn.publicationInfo.instructions.part5': 'Maximum number of publications',
  'form.issn.publicationInfo.instructions.part6': 'You can request an ISSN for a maximum of four publications with a single ISSN application form. If you need ISSNs for a larger number of publications, please contact the ISSN Agency.',
  'form.issn.publicationInfo.instructions.part7': '{icon} Please request ISSN for online version when the publication is online, or ready for publication.',
  'form.issn.publicationMedium.printed': 'Printed',
  'form.issn.publicationMedium.electronical': 'Electronical',
  'form.issn.publicationMedium.online': 'Electronical',
  'form.issn.publicationMedium.cd_rom': 'CD-ROM',
  'form.issn.publicationMedium.cdrom': 'CD-ROM',
  'form.issn.publicationMedium.other': 'Other',
  'form.issn.publicationCard.city': 'City',
  'form.issn.publicationCard.firstYear': 'Issued under this title (since year)',
  'form.issn.publicationCard.issued_from_number': 'From number (number)',
  'form.issn.publicationCard.frequency': 'Frequency',
  'form.issn.publicationCard.other': 'other, which',
  'form.issn.publicationCard.publicationType': 'Publication type',
  'form.issn.publicationCard.publicationMedium': 'Medium',
  'form.issn.publicationCard.url': 'Web-address',
  'form.issn.preview.publisherInfo': 'Publisher information',
  'form.issn.preview.name': 'Publisher name',
  'form.issn.relatedPublications': 'Related publications',
  'form.issn.preview.publicationDetails': 'Publication details',
  'form.issn.preview.versions': 'Publication versions',

  // ISSN request
  'request.issn.preview.title': '{index}. Publication - {title}',

  // TableComponent
  'table.rowsPerPage': 'Rows per page',
  'table.total': 'Total',
  'table.forms': 'Displaying',
  'table.formsOnOnePage': 'Total',
  'table.headRows.active': 'Active',
  'table.headRows.id': 'ID',
  'table.headRows.block': 'Block',
  'table.headRows.publicationType': 'Publication type',
  'table.headRows.identifier': 'Identifier',

  // Publisher registry (Kustantajarekisteri)
  'publisherRegistry.title': 'Search publisher by name',
  'publisherRegistry.headRows.activeIdentifiers': 'Active identifiers',
  'publisherRegistry.publisher.otherNameForms': 'Other name forms',
  'publisherRegistry.publisher.previousNameForms': 'Previous name forms',
  'publisherRegistry.publisher.publisherHasQuitted': 'Publishing acitivity terminated',
  'publisherRegistry.publisher.noOtherNames': 'No other names',
  'publisherRegistry.publisher.noPreviousNames': 'No previous names',
  'publisherRegistry.publisher.typeOther': 'Other publication types',
  'publisherRegistry.publisher.fileFormatOther': 'Other file formats',
  'publisherRegistry.publisher.manufacturer': 'Manufacturer',
  'publisherRegistry.publisher.run': 'Copies',
  'publisherRegistry.publisher.edition': 'Edition',
  'publisherRegistry.publisher.role': 'Role',
  'publisherRegistry.popover.isbn': 'ISBN - Books',
  'publisherRegistry.popover.ismn': 'ISMN - Sheet music',

  // ISSN publication
  'publication.issn.title': 'Search ISSN publication by title',
  'publication.issn.additionalDetails': 'Additional details',
  'publication.issn.manufacturer': 'Manufacturer',
  'publication.issn.frequency': 'Publishing frequency',
  'publication.issn.other': 'Other, which?',
  'publication.issn.firstYear': 'Issued from (year)',
  'publication.issn.issued_from_number': 'Issued from (number)',
  'publication.issn.type': 'Publication type',
  'publication.issn.anotherFormat': 'Another format',
  'publication.issn.mainSeries': 'Main series',
  'publication.issn.subSeries': 'Sub series',
  'publication.issn.previousNameForms': 'Previous name forms',
  'publication.issn.lastIssue': 'Last issue/year',

  // Modals - used in multiple places in modal components
  'modal.publicBatch.confirmation': 'Vahvistus / Bekräftelse / Confirmation',
  'modal.publicBatch.confirmation.text.part1': 'Vahvistan edustavani kustantajaa ',
  'modal.publicBatch.confirmation.text.part2': ' ja omistavani kustantajatunnuksen ',
  'modal.publicBatch.confirmation.text.part3': 'Jag bekräftar att jag representerar förlaget  ',
  'modal.publicBatch.confirmation.text.part4': ' och äger förlagsbeteckningen ',
  'modal.publicBatch.confirmation.text.part5': 'I confirm I represent ',
  'modal.publicBatch.confirmation.text.part6': ' (publisher ID {id})',

  // Service messages - used in action dispatchers (store/actions)
  'serviceMessage.registration.success': 'Registration request sent successfully',
  'serviceMessage.registration.error': 'Registration request failed',
  'serviceMessage.requestCreate.successfull': 'Request sent successfully',
  'serviceMessage.requestCreate.unsuccessfull': 'Request sending failed',
  'serviceMessage.requestQuery.unsuccessfull': 'Request query failed',
  'serviceMessage.requestRead.unsuccessfull': 'Request read failed',
  'serviceMessage.publisherRead.unsuccessfull': 'Publisher read failed',
  'serviceMessage.publisherSearch.unsuccessfull': 'Publisher search failed',
  'serviceMessage.batchRead.unsuccessfull': 'Batch read failed',
  'serviceMessage.batchQuery.unsuccessfull': 'Batches query failed',
  'serviceMessage.batchDownload.successfull': 'Downloaded successfully',
  'serviceMessage.batchDownload.unsuccessfull': 'Download failed',

  // Service messages - errors
  'serviceMessage.turnstileScript.error': 'An unknown error has occurred. Please refresh the page and try again.',

  // Turnstile info
  'form.turnstile.title': 'Important note',
  'form.turnstile.info': 'By proceeding to complete this form you agree and consent that the site is protected by an automated detection service to distinguish human users from bot users. In the process, the service provider (Cloudflare) receives information on your IP-address.',
  'form.turnstile.info.batchdownload': 'By proceeding to download the identifiers you agree and consent that the site is protected by an automated detection service to distinguish human users from bot users. In the process, the service provider (Cloudflare) receives information on your IP-address.',
  'form.turnstile.link.privacy': 'Cloudflare privacy policy',
  'form.turnstile.link.terms': 'Cloudflare terms of use'
};

export default en;
