/**
 *
 * @licstart  The following is the entire license notice for the JavaScript code in this file.
 *
 * Public UI service of Identifier Services system
 *
 * Copyright (C) 2023 University Of Helsinki (The National Library Of Finland)
 *
 * This file is part of identifier-services-ui-public
 *
 * identifier-services-ui-public program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * identifier-services-ui-public is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @licend  The above is the entire license notice
 * for the JavaScript code in this file.
 *
 */

const en = {
  // Common translations - used in multiple components
  'common.isbn': 'ISBN',
  'common.ismn': 'ISMN',
  'common.isbn-ismn': 'ISBN and ISMN',
  'common.issn': 'ISSN',
  'common.user': 'User',
  'common.users': 'Users',
  'common.publisher.isbn': 'Publisher',
  'common.publishers.isbn': 'Publishers',
  'common.publisherDetails.isbn': 'Publisher details',
  'common.publisher.issn': 'Publisher',
  'common.publishers.issn': 'Publishers',
  'common.publisherDetails.issn': 'Publisher details',
  'common.request': 'Request',
  'common.requests': 'Requests',
  'common.requestDetails': 'Request details',
  'common.publication': 'Publication',
  'common.publications': 'Publications',
  'common.publicationDetails': 'Publication details',
  'common.batch': 'List of ISBNs',
  'common.batches': 'Identifier Batches',
  'common.batchDetails': 'Identifier list details',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.true': 'Yes',
  'common.true.allLangs': 'Kyllä / Ja / Yes',
  'common.false': 'No',
  'common.false.allLangs': 'Ei / Nej / No',
  'common.noData': 'No search results',
  'common.blank': 'Blank',
  'common.search.inputPlaceholder': 'Search...',
  'common.search.searchById': 'Search by ID...',
  'common.search.searchByPublisherName': 'Search by publisher name or email...',
  'common.noValue': '-',
  'common.name': 'Name',
  'common.undefined': 'Not defined',
  'common.link': 'Link',
  'common.identifier': 'Identifier',
  'common.identifiers': 'Identifiers',
  'common.identifiersPrinted': 'Identifiers (printed)',
  'common.identifiersElectronical': 'Identifiers (electronical)',
  'common.amount': 'Amount',
  'common.status': 'Status',
  'common.id': 'ID',
  'common.contactDetails': 'Contact details',
  'common.noLink': 'Not generated',
  'common.important.info': 'Important information',
  'common.datePicker.helperText': 'E.g. 06/2023',
  'common.privacypolicy.title': 'Privacy Policy',
  'common.other': 'other',
  'common.errorPage': 'Error page',
  'common.skipLink': 'Skip to main content',
  'common.inLibrary': 'In National Library',
  'common.free': 'free of charge',
  'common.requiredField': 'Fields marked with asterisk (*) are required',
  // Numbers
  'common.one': 'One',
  'common.two': 'Two',
  'common.three': 'Three',
  'common.four': 'Four',
  // Publication languages
  'common.fin': 'Finnish',
  'common.swe': 'Swedish',
  'common.eng': 'English',
  'common.smi': 'Sami',
  'common.fre': 'French',
  'common.ger': 'German',
  'common.rus': 'Russian',
  'common.spa': 'Spanish',
  'common.mul': 'Other/bilingual',
  // Publisher's preferred languages
  'common.fi-FI': 'Finnish',
  'common.en-GB': 'English',
  'common.sv-SE': 'Swedish',
  // ISBN/ISMN publication types
  'common.BOOK': 'Book/booklet',
  'common.DISSERTATION': 'Dissertation',
  'common.MUSIC': 'Sheet music',
  'common.SHEET_MUSIC': 'Sheet music',
  'common.MAP': 'Map',
  'common.OTHER': 'Other',
  // ISSN publication types
  'common.journal': 'Journal',
  'common.newsletter': 'Newsletter',
  'common.staff_magazine': 'Staff magazine',
  'common.membership_based_magazine': 'Membership-based magazine',
  'common.newspaper': 'Newspaper',
  'common.free_paper': 'Free paper',
  'common.monography_series': 'Monograph series',
  'common.cartoon': 'Cartoon',
  'common.other_serial': 'Other (e.g. statistics, yearbook, report)',
  // ISSN publication frequency options
  'common.a': 'Yearly',
  'common.f': 'Bi-yearly',
  'common.q': 'Quarterly',
  'common.b': 'Bi-monthly',
  'common.m': 'Monthly',
  'common.w': 'Weekly',
  'common.d': 'Daily',
  'common.k': 'Continuously',
  'common.#': 'Irregular',
  'common.z': 'Other',
  // ISSN publication medium
  'common.printed': 'printed',
  'common.online': 'electronical',
  'common.cdrom': 'CD-ROM',
  // Months
  'common.month.1': 'January',
  'common.month.2': 'February',
  'common.month.3': 'March',
  'common.month.4': 'April',
  'common.month.5': 'May',
  'common.month.6': 'June',
  'common.month.7': 'July',
  'common.month.8': 'August',
  'common.month.9': 'September',
  'common.month.10': 'October',
  'common.month.11': 'November',
  'common.month.12': 'December',

  // Home page
  'homePage.title': 'Identifier Services',
  'homePage.description.part1': 'International standard identifiers (ISBN, ISSN and ISMN) uniquely identify publications. Identifiers are used, for example, in publishing industry\'s ordering and distribution systems.',
  'homePage.description.part2': 'ISBN identifies books, ISMN notated music publications and ISSN serial publications.',
  'homePage.description.part3': 'In Finland, these identifiers are applied for from the Finnish ISBN and ISSN Agencies operating at the National Library of Finland. The identifiers are free of charge.',
  'homePage.link': 'More about {link}',
  'homePage.instructions.title': 'Instructions for completing the forms',
  'homePage.instructions.main.text': 'If you publish regularly (for example, one or more publications a year) and you are not yet a member of the ISBN/ISMN system, please complete both the electronic publisher registration form (ISBN/ISMN) and the ISBN/ISMN application form.{lineBreak}{lineBreak}If your publishing activities are occasional or you have already joined the ISBN/ISMN system, please complete the ISBN/ISMN application for books and sheet music only.{lineBreak}{lineBreak}Information on publishers entered in the ISBN/ISMN system is published in the international databases Global Register of Publishers and/or Music Publishers\' International ISMN Database. This information is also used by the Finnish ISBN Agency and published on its website.',
  'homePage.instructions.isbn-ismn.text': 'An ISBN identifies books and an ISMN identifies notated music publications intended for public use. The Finnish national ISBN Agency is responsible for handing out ISBNs and ISMNs in Finland. The Agency maintains a national publisher register and provides information about Finnish publishers for national and international use.{lineBreak}{lineBreak}Identifiers as a part of metadata serve the publishing industry and the library sector in their entirety, supporting identification, processing and availability of publications. Identifiers are used, for example, in publishing industry\'s ordering and distribution systems to speed up the identification of publications - as well as in international and domestic joint catalogues, bibliographies, library lending systems and information retrieval.{lineBreak}{lineBreak}Each book or sheet music publication, each different publication form (printed, audio-visual, digital) and each edition containing changes are issued a separate ISBN or ISMN. This promotes identification of publications in the publishing industry\'s distribution chain and ensures that customers get the desired publication at their disposal. Publication format may be a printed book or an audio-visual or electronic recording.',
  'homePage.instructions.issn.text': 'An ISSN identifies continuously published publications, such as journals and series. The Finnish national ISSN Agency is responsible for providing the identifiers in Finland and sends the information about publications that have received an ISSN to the {link} database.{lineBreak}{lineBreak}Identifiers as a part of metadata serve the publishing industry and the library sector in their entirety, supporting identification, processing and availability of publications.{lineBreak}{lineBreak}Identifiers are used, for example, in publishing industry\'s ordering and distribution systems to speed up the identification of publications as well as in international and domestic joint catalogues, bibliographies, library lending systems and information retrieval. An ISSN is inseparable from the title of the publication; if the title of the publication changes, the identifier must also be changed. A separate ISSN is given to different forms of publication.',

  // Menu bar
  'menu.mobile': 'Menu',
  'menu.home': 'Home',
  'menu.publisherRegistry': 'Publisher Register',
  'menu.forms': 'Forms',
  'menu.forms.publisherRegistration': 'Publisher registration form',
  'menu.forms.publicationRegistration': 'ISBN-/ISMN-forms',
  'menu.forms.issnPublicationRegistration': 'ISSN-form',
  'menu.forms.publicationRegistration.isbn-ismn': 'ISBN/ISMN application for books and sheet music',
  'menu.forms.publicationRegistration.issn': 'ISSN application for periodicals',
  'menu.forms.contactInformationChange': 'Change contact information (ISBN/ISMN)',

  // Footer
  'footer.privacyPolicy': 'Privacy policy',
  'footer.accessibilityStatement': 'Accessibility statement',
  'footer.library': 'The National Library of Finland',
  'footer.address': 'PL 15 (Unioninkatu 36)',
  'footer.zip': '00014 University of Helsinki',
  'footer.contact': 'Contacts',
  'footer.copyright': '© The National Library of Finland 2023',
  'footer.socials': 'Follow on social media',

  // Alt texts (Kuvatekstit)
  'altText.logo.library': 'The official logo of The National Library of Finland',

  // Ranges (Tunnistelohkot)
  'ranges.identifierType': 'Type',

  // Error messages
  'error.field.required': 'Required',
  'error.format.issn': 'Invalid ISSN-identifier',
  'error.format.publisherIdentifierStr': 'Invalid publisher identifier',
  'error.format.phone': 'Invalid phone number',
  'error.format.city': 'Invalid city',
  'error.format.publishingActivityAmount': 'Max. 5 characters',
  'error.format.copies': 'Max. 10 characters',
  'error.format.maxLength': 'Given value is too long',
  'error.format.minLength': 'Given value is too short',
  'error.format.integer': 'Given value must be a number',
  'error.format.integer.twoDigits': 'Given value must be a number with two digits (e.g. 39)',
  'error.format.year': 'Invalid year',
  'error.format.email': 'Invalid email address',
  'error.format.www': 'Invalid URL, please use http:// or https://',
  'error.format.edition': 'Max 2 characters',
  'error.postalAddress.zip.format': 'Invalid postal code',
  'error.postalAddress.city.format': 'Invalid city',
  'error.publicationRegistrationIsbnIsmn.form.availability': 'ISBN identifiers are only granted for publications intended for public use',
  'error.publicationRegistrationIsbnIsmn.form.otherUniversitites': 'ISBN Agency grants ISBN identifiers only for dissertations made at the University of Helsinki',
  'error.date.invalid': 'Invalid date',
  'error.date.min': 'The date to be entered must be after current date',
  'error.identifierBatch.invalid': 'Loading of identifier batch failed. Please try again or contact customer service',
  'error.formEdit': 'There are errors in the form, please check the fields marked in red: ',
  'error.emptyField': ' ',
  'error.classification.maxAmount': 'You can add max. 5 classification keywords',

  // Error page texts
  'errorPage.header': 'Sorry, something went wrong',
  'errorPage.message.serviceDown': 'The service is down. Please try again later. If the problem persists, please contact customer service',
  'errorPage.message.serviceUnderMaintenance': 'The service is under maintenance. Please try again later. If the problem persists, please contact customer service',
  'errorPage.message.defaultError': 'Unknown error. Please try again or contact customer service',
  'errorPage.message.generatingMessageFailed': 'Operation failed, please try again or contact customer service',
  'errorPage.publicationRequestError': 'The page could not be loaded. Please check the address and try again. If the problem persists, please contact customer service',
  'errorPage.accessdenied.heading': 'Access denied',
  'errorPage.accessdenied.message': 'You do not have permission to access this page',
  'errorPage.admin.genericError': 'System error. Please contact system administrator for assistance',

  // Common form translations - used in multiple forms
  'form.common.name': 'Publisher name',
  'form.common.otherNames': 'Other names',
  'form.common.previousNames': 'Previous names',
  'form.common.phone': 'Phone number',
  'form.common.email': 'Email',
  'form.common.contactPerson': 'Contact person',
  'form.common.website': 'Website',
  'form.common.address': 'Address',
  'form.common.addressLine1': 'Address 2',
  'form.common.zip': 'Postal code',
  'form.common.city': 'City',
  'form.common.affiliates': 'Affiliates',
  'form.common.affiliateOf': 'Affiliate of',
  'form.common.distributors': 'Distributors',
  'form.common.distributorOf': 'Distributor of',
  'form.common.currentYear': 'Estimated publication amount (this year)',
  'form.common.nextYear': 'Estimated publication amount (next year)',
  'form.common.classification': 'Classification',
  'form.common.classificationKeywords': 'Keywords',
  'form.common.classificationOther': 'Other classification',
  'form.common.classificationCodes': 'Classification codes',
  'form.common.publisherIdentifier': 'Publisher identifier',
  'form.common.publisherIdentifiers': 'Publisher identifiers',
  'form.common.title': 'Title',
  'form.common.subtitle': 'Subtitle',
  'form.common.authorName': 'Author name',
  'form.common.selectFormat': 'Select format',
  'form.common.publicationMonth': 'Publication month',
  'form.common.publicationYear': 'Publication year',
  'form.common.language': 'Language',
  'form.common.identifier': 'Identifier',
  'form.common.volume': 'Volume',
  'form.common.type': 'Type of publication',
  'form.common.publishingActivities': 'Publishing activities',
  'form.common.instruction.multipleSelect': 'Select one or more options from the list',
  'form.common.instruction.createableSelect': 'To add a new option, type the name of the option and press Enter',
  'form.common.basicInfo': 'Basic information',
  'form.common.postalAddress': 'Postal address',
  'form.common.activeIdentifier': 'Active {type}-identifier',
  'form.common.organizationDetails': 'Organisation details',
  'form.common.frequency': 'Publication frequency',
  'form.common.activity': 'Publishing activity',
  'form.common.additionalDetails': 'Additional details',
  'form.common.noAdditionalDetails': 'No additional details',
  'form.common.createdAndUpdated': 'Created and updated',
  'form.common.created': 'Created',
  'form.common.createdBy': 'Created by',
  'form.common.modified': 'Modified',
  'form.common.modifiedBy': 'Modified by',
  'form.common.printFormat': 'Print format',
  'form.common.fileFormat': 'File format',
  'form.common.subRangeType': 'Type of publisher identifier',
  'form.common.otherInfo': 'Other information',
  'form.common.format': 'Format',
  'form.common.publicationCity': 'Place of publication',
  'form.common.updated': 'Updated',
  'form.common.confirmation': 'Confirmation (old system)',
  'form.common.scale': 'Scale',
  'form.common.archiveRecord': 'Archive record',
  'form.common.url': 'Web address',

  // Form edition translations (Painos)
  'form.edition.first': 'First',
  'form.edition.second': 'Second',
  'form.edition.third': 'Third',
  'form.edition.fourth': 'Fourth',
  'form.edition.fifth': 'Fifth',
  'form.edition.sixth': 'Sixth',
  'form.edition.seventh': 'Seventh',
  'form.edition.eighth': 'Eighth',
  'form.edition.ninth': 'Ninth',
  'form.edition.tenth': 'Tenth',
  'form.edition.eleventh': 'Eleventh',
  'form.edition.twelfth': 'Twelfth',
  'form.edition.thirteenth': 'Thirteenth',
  'form.edition.fourteenth': 'Fourteenth',
  'form.edition.fifteenth': 'Fifteenth',

  // Printed publication format (Kansityyppi)
  'form.printFormat.paperback': 'Paperback',
  'form.printFormat.hardback': 'Hardback',
  'form.printFormat.spiral_binding': 'Spiral binding',
  'form.printFormat.other_print': 'Other (printed)',

  // File format (Tiedostomuoto)
  'form.fileFormat.pdf': 'PDF',
  'form.fileFormat.epub': 'EPUB',
  'form.fileFormat.cd_rom': 'CD-ROM',
  'form.fileFormat.mp3': 'MP3',
  'form.fileFormat.other': 'Other (electronical)',

  // Frequency (Julkaisutiheys)
  'form.frequency.yearly': 'Yearly',
  'form.frequency.monthly': 'Monthly',
  'form.frequency.weekly': 'Weekly',
  'form.frequency.daily': 'Daily',
  'form.frequency.biyearly': 'Bi-yearly',
  'form.frequency.quarterly': 'Quarterly',
  'form.frequency.bimonthly': 'Bi-monthly',
  'form.frequency.irregular': 'Irregular',
  'form.frequency.continuously': 'Continuously',
  'form.frequency.other': 'Other',

  // Button labels
  'form.button.label.back': 'Back',
  'form.button.label.next': 'Next',
  'form.button.label.submit': 'Submit',
  'form.button.label.proceed': 'Continue',
  'form.button.label.add': 'Add',
  'form.button.label.addPublication': 'Add publication',
  'form.button.label.delete': 'Delete',
  'form.button.label.downloadAsTextfile': 'Download as text file',
  'form.button.label.showIdentifiers': 'Show Identifiers',

  // Publisher registration form (Kustantajan liittymislomake)
  'form.publisherRegistration.instructions.title': 'When joining the ISBN system, the publisher commits to the following obligations: ',
  'form.publisherRegistration.instructions.note0': 'An ISBN must appear on all the publications published.',
  'form.publisherRegistration.instructions.note1.part1': 'The ISBN should be printed as advised on the ',
  'form.publisherRegistration.instructions.note1.link': 'ISBN Agency\'s website',
  'form.publisherRegistration.instructions.note1.part2': '.',
  'form.publisherRegistration.instructions.note2': 'The publisher keeps a list of its publications sorted according to their ISBN numbers.',
  'form.publisherRegistration.instructions.note3': 'The publisher will send a copy of each publication to the Finnish ISBN Agency immediately after publication.',
  'form.publisherRegistration.instructions.note4': 'Entered publisher information is published in the international databases Global Register of Publishers and/or Music Publishers\' International ISMN Database. The information is also used by the Finnish ISBN Agency and published on its website.',
  'form.publisherRegistration.title': 'Publisher registration',
  'form.publisherRegistration.stepper.label.basicInformation': 'Basic information',
  'form.publisherRegistration.stepper.label.publishingActivities': 'Publishing activities',
  'form.publisherRegistration.stepper.label.organizationDetails': 'Organisation details',
  'form.publisherRegistration.stepper.label.preview': 'Preview',
  'form.publisherRegistration.basicInformation.name': 'Publisher name*',
  'form.publisherRegistration.basicInformation.address': 'Postal address*',
  'form.publisherRegistration.basicInformation.city': 'City*',
  'form.publisherRegistration.basicInformation.zip': 'Postal code*',
  'form.publisherRegistration.basicInformation.phone': 'Phone number*',
  'form.publisherRegistration.basicInformation.publisherEmail': 'Email*',
  'form.publisherRegistration.basicInformation.website': 'Website',
  'form.publisherRegistration.basicInformation.contactPerson': 'Contact person*',
  'form.publisherRegistration.basicInformation.email': 'Email*',
  'form.publisherRegistration.basicInformation.otherNames': 'Other name forms',
  'form.publisherRegistration.publishingActivities.currentYear': 'Please estimate the number of publications you publish this year*',
  'form.publisherRegistration.publishingActivities.nextYear': 'Please estimate the number of publications you publish next year*',
  'form.publisherRegistration.publishingActivities.classification': 'Classification codes*',
  'form.publisherRegistration.publishingActivities.classification.placeholder': 'Add classification keyword*',
  'form.publisherRegistration.publishingActivities.classificationOther': 'Other keywords',
  'form.publisherRegistration.organization.affiliates': 'Affiliates',
  'form.publisherRegistration.organization.affiliateOf': 'Affiliate of',
  'form.publisherRegistration.organization.distributors': 'Distributors',
  'form.publisherRegistration.organization.distributorOf': 'Distributor of',
  'form.publisherRegistration.classification.general': 'General',
  'form.publisherRegistration.classification.book-business-lib': 'Book business, Libraries',
  'form.publisherRegistration.classification.text-books': 'Text books',
  'form.publisherRegistration.classification.children-book': 'Children\'s books',
  'form.publisherRegistration.classification.official-publication': 'Official publications',
  'form.publisherRegistration.classification.university-publication': 'University publications',
  'form.publisherRegistration.classification.electronic-publication': 'Electronic publications',
  'form.publisherRegistration.classification.audiovisual': 'Audiovisual material. Videos',
  'form.publisherRegistration.classification.philosophy': 'Philosophy',
  'form.publisherRegistration.classification.psychology': 'Psychology',
  'form.publisherRegistration.classification.paranormal': 'Paranormal phenomena, Occultism, Astrology',
  'form.publisherRegistration.classification.religion': 'Religion, Theology',
  'form.publisherRegistration.classification.christianity': 'Christianity',
  'form.publisherRegistration.classification.orthodox': 'The Ortodox Church',
  'form.publisherRegistration.classification.other-religions': 'Other religions',
  'form.publisherRegistration.classification.social-science': 'Social Science, Sociology',
  'form.publisherRegistration.classification.political-studies': 'Political Studies, International Politics',
  'form.publisherRegistration.classification.military': 'Military Science',
  'form.publisherRegistration.classification.sociology': 'Sociology',
  'form.publisherRegistration.classification.economics': 'Economics',
  'form.publisherRegistration.classification.law': 'Law',
  'form.publisherRegistration.classification.public-administration': 'Public administration',
  'form.publisherRegistration.classification.education': 'Education',
  'form.publisherRegistration.classification.ethnography': 'Ethnography, Folklore',
  'form.publisherRegistration.classification.local-history': 'Local history research',
  'form.publisherRegistration.classification.social-politics': 'Social Politics, Welfare',
  'form.publisherRegistration.classification.mass-media': 'Mass Media',
  'form.publisherRegistration.classification.literature': 'Literature',
  'form.publisherRegistration.classification.fiction': 'Fiction',
  'form.publisherRegistration.classification.poetry': 'Poetry',
  'form.publisherRegistration.classification.cartoons': 'Cartoons',
  'form.publisherRegistration.classification.science-fiction': 'Science Fiction',
  'form.publisherRegistration.classification.crime-fiction': 'Crime Fiction',
  'form.publisherRegistration.classification.linguistic': 'Linguistic',
  'form.publisherRegistration.classification.sexual-minorities': 'Sexual Minorities',
  'form.publisherRegistration.classification.minorities': 'Minorities',
  'form.publisherRegistration.classification.science': 'Science',
  'form.publisherRegistration.classification.mathematics': 'Mathematics, Statistics',
  'form.publisherRegistration.classification.astronomy': 'Astronomy',
  'form.publisherRegistration.classification.physics': 'Physics',
  'form.publisherRegistration.classification.chemistry': 'Chemistry',
  'form.publisherRegistration.classification.geology': 'Geology',
  'form.publisherRegistration.classification.biology': 'Biology',
  'form.publisherRegistration.classification.zoology': 'Zoology',
  'form.publisherRegistration.classification.botany': 'Botany',
  'form.publisherRegistration.classification.environmental-studies': 'Environmental Studies, Conservation',
  'form.publisherRegistration.classification.technology': 'Technology',
  'form.publisherRegistration.classification.engineering': 'Engineering Technology',
  'form.publisherRegistration.classification.industry': 'Industry',
  'form.publisherRegistration.classification.construction': 'Construction',
  'form.publisherRegistration.classification.transport': 'Transport, Post',
  'form.publisherRegistration.classification.information-tech': 'Information Technology',
  'form.publisherRegistration.classification.medicine': 'Medicine, Psychiatry',
  'form.publisherRegistration.classification.odontology': 'Odontology',
  'form.publisherRegistration.classification.veteriniry': 'Veterinary Medicine',
  'form.publisherRegistration.classification.pharmacology': 'Pharmacology, Homeopathy',
  'form.publisherRegistration.classification.forestry': 'Forestry',
  'form.publisherRegistration.classification.agriculture': 'Agriculture',
  'form.publisherRegistration.classification.handicraft': 'Handicraft',
  'form.publisherRegistration.classification.art': 'Art',
  'form.publisherRegistration.classification.performing-art': 'Performing Art',
  'form.publisherRegistration.classification.theatre': 'Theatre, Film',
  'form.publisherRegistration.classification.dance': 'Dance',
  'form.publisherRegistration.classification.visual-art': 'Visual Arts',
  'form.publisherRegistration.classification.art-history': 'Art History',
  'form.publisherRegistration.classification.architecture': 'Architecture, Industrial Art',
  'form.publisherRegistration.classification.fashion': 'Fashion',
  'form.publisherRegistration.classification.music': 'Music',
  'form.publisherRegistration.classification.antique': 'Antiques, Collecting',
  'form.publisherRegistration.classification.city-regional': 'City and Regional Planning',
  'form.publisherRegistration.classification.leisure-hobbies': 'Leisure and Hobbies',
  'form.publisherRegistration.classification.sports': 'Sports',
  'form.publisherRegistration.classification.games': 'Games',
  'form.publisherRegistration.classification.hunting-fishing': 'Hunting and Fishing',
  'form.publisherRegistration.classification.gardening': 'Gardening',
  'form.publisherRegistration.classification.home-economic': 'Home Economics',
  'form.publisherRegistration.classification.health-beauty': 'Health and Beauty',
  'form.publisherRegistration.classification.photography': 'Photography',
  'form.publisherRegistration.classification.tourism': 'Tourism, Travel',
  'form.publisherRegistration.classification.humour': 'Humour',
  'form.publisherRegistration.classification.history': 'History',
  'form.publisherRegistration.classification.geography': 'Geography',
  'form.publisherRegistration.classification.map-atlases': 'Maps and Atlases',
  'form.publisherRegistration.classification.archeology': 'Archeology',
  'form.publisherRegistration.classification.genealogy': 'Genealogy',
  'form.publisherRegistration.classification.numismatics': 'Numismatics',
  'form.publisherRegistration.preview.publishingFrequency': 'Publishing frequency',
  'form.publisherRegistration.preview.organizationDetails': 'Organisation details',
  'form.publisherRegistration.preview.postalAddress': 'Postal address',
  'form.publisherRegistration.preview.publisherInformation': 'Publisher information',
  'form.publisherRegistration.card.affiliates': 'Do you have any affiliated companies in Finland or abroad? Please provide the names and addresses of the companies and an estimate of the annual publication amounts.',
  'form.publisherRegistration.card.distributors': 'Do you have any foreign or Finnish distributors? Please provide the names and addresses of the companies.',

  // ISBN/ISMN-form
  'form.isbnIsmn.title': 'Apply for ISBN or ISMN identifier',
  'form.isbnIsmn.stepper.label.availabilityInformation': 'Basic information',
  'form.isbnIsmn.stepper.label.publisherBasicInfo': 'Publisher',
  'form.isbnIsmn.stepper.label.publishingActivities': 'Publishing activities',
  'form.isbnIsmn.stepper.label.basicInformation': 'Publication',
  'form.isbnIsmn.stepper.label.authorInformation': 'Authors',
  'form.isbnIsmn.stepper.label.seriesInformation': 'Series',
  'form.isbnIsmn.stepper.label.formatBasic': 'Publication format',
  'form.isbnIsmn.stepper.label.additionalDetails': 'Additional details',
  'form.isbnIsmn.stepper.label.dissertationFormat': 'Dissertation format',
  'form.isbnIsmn.stepper.label.contactInfo': 'Contacts',
  'form.isbnIsmn.stepper.label.universityInformation': 'University information',
  'form.isbnIsmn.stepper.label.preview': 'Preview',
  'form.isbnIsmn.availability.publicationsPublic': 'Is your publication intended for public use (e.g., for library use or sale in bookshops) or will it be made otherwise available to the public? If your publication is a web-version or an ebook, will it be free to download or to buy?*',
  'form.isbnIsmn.availability.type': 'Publication is*',
  'form.isbnIsmn.availability.type.option.book': 'Book/booklet',
  'form.isbnIsmn.availability.type.option.dissertation': 'Dissertation',
  'form.isbnIsmn.availability.type.option.sheet_music': 'Sheet music',
  'form.isbnIsmn.availability.type.option.map': 'Map',
  'form.isbnIsmn.availability.type.option.other': 'Other',
  'form.isbnIsmn.availability.publicationsPublic.label': 'Is your publication intended for public use?',
  'form.isbnIsmn.availability.type.label': 'Publication is',
  'form.isbnIsmn.publisherInfo.name': 'Publisher name*',
  'form.isbnIsmn.publisherInfo.publisherIdentifierStr': 'Publisher identifier',
  'form.isbnIsmn.publisherInfo.address': 'Address*',
  'form.isbnIsmn.publisherInfo.zip': 'Postal code*',
  'form.isbnIsmn.publisherInfo.city': 'City*',
  'form.isbnIsmn.publisherInfo.phone': 'Phone number*',
  'form.isbnIsmn.publisherInfo.contactPerson': 'Contact person*',
  'form.isbnIsmn.publisherInfo.email': 'Email*',
  'form.isbnIsmn.publishingActivities.hasPublishedBefore': 'Have you published previously?',
  'form.isbnIsmn.publishingActivities.occasionalOrContinuous': 'Are your publishing activities occasional/continuous?*',
  'form.isbnIsmn.publishingActivities.thisYear': 'How many publications do you publish annually?',
  'form.isbnIsmn.publishingActivities.option.occasional': 'Occasional',
  'form.isbnIsmn.publishingActivities.option.continuous': 'Continuous',
  'form.isbnIsmn.university.isHelsinki': 'Is the dissertation made at the University of Helsinki?',
  'form.isbnIsmn.university.contactInfo.contactPerson': 'Contact person*',
  'form.isbnIsmn.university.contactInfo.address': 'Address*',
  'form.isbnIsmn.university.contactInfo.zip': 'Postal code*',
  'form.isbnIsmn.university.contactInfo.city': 'City*',
  'form.isbnIsmn.university.contactInfo.phone': 'Phone number*',
  'form.isbnIsmn.university.contactInfo.email': 'Email*',
  'form.isbnIsmn.publicationInfo.title': 'Title*',
  'form.isbnIsmn.publicationInfo.subtitle': 'Subtitle',
  'form.isbnIsmn.publicationInfo.language': 'Language*',
  'form.isbnIsmn.publicationInfo.scale': 'Scale',
  'form.isbnIsmn.publicationInfo.publicationMonth': 'Month of publication*',
  'form.isbnIsmn.publicationInfo.publicationYear': 'Year of publication*',
  'form.isbnIsmn.authors.givenName': 'Authors first name*',
  'form.isbnIsmn.authors.familyName': 'Authors last name*',
  'form.isbnIsmn.authors.role': 'Role*',
  'form.isbnIsmn.authors.role.option.author': 'Author',
  'form.isbnIsmn.authors.role.option.illustrator': 'Illustrator',
  'form.isbnIsmn.authors.role.option.translator': 'Translator',
  'form.isbnIsmn.authors.role.option.editor': 'Editor',
  'form.isbnIsmn.authors.card.name': 'Name:',
  'form.isbnIsmn.authors.card.roles': 'Roles:',
  'form.isbnIsmn.authors.card.noAuthors': 'Add author by filling the information and press the \'Add\' button',
  'form.isbnIsmn.authors.card.addMoreAuthors': 'Add more authors by filling the information and press the \'Add\' button. Max. 4 authors are allowed. Other authors will be considered when the publications arrives to the National Library.',
  'form.isbnIsmn.authors.card.maxAuthors': 'You have added maximum amount of authors. Other authors will be considered when the publications arrives to the National Library.',
  'form.isbnIsmn.series.title': 'Series title',
  'form.isbnIsmn.series.volume': 'Volume number',
  'form.isbnIsmn.format.label': 'Publication format*',
  'form.isbnIsmn.format.option.print': 'Printed',
  'form.isbnIsmn.format.option.electronical': 'Electronical',
  'form.isbnIsmn.format.option.print_electronical': 'Both printed and electronical',
  'form.isbnIsmn.format.dissertation.option.printed': 'Printed (paperback)',
  'form.isbnIsmn.format.dissertation.option.electronic': 'Electronical (PDF)',
  'form.isbnIsmn.format.dissertation.option.both': 'Both printed (paperback) and electronical (PDF)',
  'form.isbnIsmn.format.dissertation.option.printed.edition': 'Edition',
  'form.isbnIsmn.format.dissertation.option.printed.manufacturer': 'Manufacturer',
  'form.isbnIsmn.format.dissertation.option.printed.city': 'City',
  'form.isbnIsmn.format.printFormat': 'Cover format*',
  'form.isbnIsmn.format.printFormat.other': 'Other cover format*',
  'form.isbnIsmn.format.printFormat.printed.manufacturer': 'Manufacturer',
  'form.isbnIsmn.format.printFormat.printed.city': 'City',
  'form.isbnIsmn.format.printFormat.printed.edition': 'Edition',
  'form.isbnIsmn.format.printFormat.printed.copies': 'Copies',
  'form.isbnIsmn.format.fileFormat': 'File format*',
  'form.isbnIsmn.format.fileFormat.other': 'Other file format*',
  'form.isbnIsmn.additionalDetails': 'Additional details',
  'form.isbnIsmn.preview.publisherDetails': 'Publisher details',
  'form.isbnIsmn.preview.publicationInfo': 'Publication details',
  'form.isbnIsmn.preview.universityName': 'University',
  'form.isbnIsmn.preview.helsinki': 'University of Helsinki',
  'form.isbnIsmn.preview.previouslyPublished': 'Has published previously',
  'form.isbnIsmn.preview.thisYear': 'Estimated number of publications this year',
  'form.isbnIsmn.preview.format': 'Format',
  'form.isbnIsmn.preview.formatDetails': 'Publication format',
  'form.isbnIsmn.preview.printFormat': 'Cover format',
  'form.isbnIsmn.preview.printFormatOther': 'Other cover format',
  'form.isbnIsmn.preview.fileFormat': 'File format',
  'form.isbnIsmn.preview.fileformatOther': 'Other file format',
  'form.isbnIsmn.preview.authors': 'Authors',
  'form.isbnIsmn.preview.additionalDetails': 'Additional details',
  'form.isbnIsmn.preview.manufacturer': 'Manufacturer',
  'form.isbnIsmn.preview.city': 'City',
  'form.isbnIsmn.preview.edition': 'Edition',
  'form.isbnIsmn.preview.run': 'Copies',
  'form.isbnIsmn.preview.seriesDetails': 'Series details',
  'form.isbnIsmn.preview.publicationDetails': 'Basic information',
  'form.isbnIsmn.preview.isPublic': 'Public',
  'form.isbnIsmn.card.universityOfHelsinki': 'Before you fill in this ISBN application form, please check at your department/faculty if you get an ISBN from your university. If needed, please contact ISBN Agency.',
  'form.isbnIsmn.card.otherUniversity': 'Before you fill in this ISBN application form, please check at your department/faculty if you get an ISBN from there. If needed, please contact ISBN Agency for more information.',
  'form.isbnIsmn.card.publicationIsPublic': 'If your publication is intended for private use only (e.g., for friends, family or the internal use of an association or organisation), publication will not be assigned an ISBN.',
  'form.isbnIsmn.card.editionInfo': 'Information about new editions',
  'form.isbnIsmn.card.publicationInfo': 'An ISBN cannot be requested after the book is printed, or published online.',
  'form.isbnIsmn.card.seriesInfo': 'Enter series details if the publication is part of a series.',
  'form.isbnIsmn.instructions': 'Information on publishers entered in the ISBN/ISMN system is published in the international databases Global Register of Publishers and/or Music Publishers\' International ISMN Database. This information is also used by the Finnish ISBN Agency and published on its website.',

  // ISSN-form
  'form.issn.title': 'ISSN request form',
  'form.issn.stepper.label.publisherInformation': 'Publisher information',
  'form.issn.stepper.label.publicationInformation_1': '1. Publication information',
  'form.issn.stepper.label.publicationInformation_2': '2. Publication information',
  'form.issn.stepper.label.publicationInformation_3': '3. Publication information',
  'form.issn.stepper.label.publicationInformation_4': '4. Publication information',
  'form.issn.stepper.label.publicationVersions': 'Amount of publication versions',
  'form.issn.stepper.label.publicationVersionsCheck': 'Other versions (check)',
  'form.issn.stepper.label.preview': 'Preview',
  'form.issn.versionInfo.number_of_versions': 'Amount of publication versions',
  'form.issn.publisherInfo.name': 'Publisher name*',
  'form.issn.publisherInfo.contact_person': 'Contact person*',
  'form.issn.publisherInfo.email': 'Email*',
  'form.issn.publisherInfo.phone': 'Phone number*',
  'form.issn.publisherInfo.address': 'Address*',
  'form.issn.publisherInfo.zip': 'Postal code*',
  'form.issn.publisherInfo.city': 'City*',
  'form.issn.publicationInfo.title': 'Title*',
  'form.issn.publicationInfo.title.instructions': 'ISSN is linked to the title of the publication. The title must be permanent and it must be printed in the publication.',
  'form.issn.publicationInfo.subtitle': 'Subtitle',
  'form.issn.publicationInfo.place_of_publication': 'Place of publication*',
  'form.issn.publicationInfo.printer': 'Printing house',
  'form.issn.publicationInfo.issued_from_year': 'Issued under this title (since year)*',
  'form.issn.publicationInfo.issued_from_number': 'From number*',
  'form.issn.publicationInfo.frequency': 'Publishing frequency*',
  'form.issn.publicationInfo.language': 'Language*',
  'form.issn.publicationInfo.publication_type': 'Publication type*',
  'form.issn.publicationInfo.other': 'other, which*',
  'form.issn.publicationInfo.medium': 'Publication form/Medium*',
  'form.issn.publicationInfo.url': 'If the publication is issued online, provide web-address*',
  'form.issn.publicationInfo.previous': 'Previous title*',
  'form.issn.publicationInfo.issn': 'Previous ISSN',
  'form.issn.publicationInfo.last_issue': 'The last issue under this title was (issue/year)*',
  'form.issn.publicationInfo.main_series': 'Title of the main series*',
  'form.issn.publicationInfo.main_series_issn': 'ISSN of the main series',
  'form.issn.publicationInfo.subseries': 'Title of the subseries*',
  'form.issn.publicationInfo.subseries_issn': 'ISSN of the subseries',
  'form.issn.publicationInfo.another_medium': 'Title of another medium*',
  'form.issn.publicationInfo.another_medium_issn': 'ISSN of another medium',
  'form.issn.publicationInfo.additional_info': 'Additional details',
  'form.issn.publicationInfo.publication_was_issued': 'Is there a previous title for the publication? ',
  'form.issn.publicationInfo.publication_has_main_series': 'Is the publication part of the main series?',
  'form.issn.publicationInfo.publication_has_subseries': 'Does the publication have subseries?',
  'form.issn.publicationInfo.publication_has_another_medium': 'Has the publication already been published in another form/medium?',
  'form.issn.publicationInfo.publication_has_another_medium.instructions': 'If the same publication was issued in another form/medium, add its information here.',
  'form.issn.publicationInfo.instructions.part1': 'Publication in several media',
  'form.issn.publicationInfo.instructions.part2': 'If the same publication is regularly issued in another form/medium (print, online), it will need its own ISSN. Enter details on each form/medium separately by choosing the correct amount of publication versions.{lineBreak}{lineBreak}',
  'form.issn.publicationInfo.instructions.part3': 'Publication in several languages',
  'form.issn.publicationInfo.instructions.part4': 'If the same publication is issued in several languages, language version needs an ISSN of its own. Enter details on each language version separately by choosing the correct amount of publication versions.',
  'form.issn.publicationInfo.instructions.part5': 'Maximum number of publications',
  'form.issn.publicationInfo.instructions.part6': 'You can request an ISSN for a maximum of four publications with a single ISSN application form. If you need ISSNs for a larger number of publications, please contact the ISSN Agency.',
  'form.issn.publicationInfo.instructions.part7': '{icon} Please request ISSN for online version when the publication is online, or ready for publication.',
  'form.issn.publicationMedium.printed': 'Printed',
  'form.issn.publicationMedium.electronical': 'Electronical',
  'form.issn.publicationMedium.online': 'Electronical',
  'form.issn.publicationMedium.cd_rom': 'CD-ROM',
  'form.issn.publicationMedium.cdrom': 'CD-ROM',
  'form.issn.publicationMedium.other': 'Other',
  'form.issn.publicationCard.city': 'City',
  'form.issn.publicationCard.firstYear': 'Issued under this title (since year)',
  'form.issn.publicationCard.issued_from_number': 'From number (number)',
  'form.issn.publicationCard.frequency': 'Frequency',
  'form.issn.publicationCard.other': 'other, which',
  'form.issn.publicationCard.publicationType': 'Publication type',
  'form.issn.publicationCard.publicationMedium': 'Medium',
  'form.issn.publicationCard.url': 'Web-address',
  'form.issn.preview.publisherInfo': 'Publisher information',
  'form.issn.preview.name': 'Publisher name',
  'form.issn.relatedPublications': 'Related publications',
  'form.issn.preview.publicationDetails': 'Publication details',
  'form.issn.preview.versions': 'Publication versions',

  // ISSN request
  'request.issn.preview.title': '{index}. Publication - {title}',

  // TableComponent
  'table.rowsPerPage': 'Rows per page',
  'table.total': 'Total',
  'table.forms': 'Displaying',
  'table.formsOnOnePage': 'Total',
  'table.headRows.active': 'Active',
  'table.headRows.id': 'ID',
  'table.headRows.block': 'Block',
  'table.headRows.publicationType': 'Publication type',
  'table.headRows.identifier': 'Identifier',

  // Publisher registry (Kustantajarekisteri)
  'publisherRegistry.title': 'Search publisher by name',
  'publisherRegistry.headRows.activeIdentifiers': 'Active identifiers',
  'publisherRegistry.publisher.otherNameForms': 'Other name forms',
  'publisherRegistry.publisher.previousNameForms': 'Previous name forms',
  'publisherRegistry.publisher.publisherHasQuitted': 'Publishing activity terminated',
  'publisherRegistry.publisher.noOtherNames': 'No other names',
  'publisherRegistry.publisher.noPreviousNames': 'No previous names',
  'publisherRegistry.publisher.typeOther': 'Other publication types',
  'publisherRegistry.publisher.fileFormatOther': 'Other file formats',
  'publisherRegistry.publisher.manufacturer': 'Manufacturer',
  'publisherRegistry.publisher.run': 'Copies',
  'publisherRegistry.publisher.edition': 'Edition',
  'publisherRegistry.publisher.role': 'Role',
  'publisherRegistry.popover.isbn': 'ISBN - Books',
  'publisherRegistry.popover.ismn': 'ISMN - Sheet music',

  // ISSN publication
  'publication.issn.title': 'Search ISSN publication by title',
  'publication.issn.additionalDetails': 'Additional details',
  'publication.issn.manufacturer': 'Manufacturer',
  'publication.issn.frequency': 'Publishing frequency',
  'publication.issn.other': 'Other, which?',
  'publication.issn.firstYear': 'Issued from (year)',
  'publication.issn.issued_from_number': 'Issued from (number)',
  'publication.issn.type': 'Publication type',
  'publication.issn.anotherFormat': 'Another format',
  'publication.issn.mainSeries': 'Main series',
  'publication.issn.subSeries': 'Sub series',
  'publication.issn.previousNameForms': 'Previous name forms',
  'publication.issn.lastIssue': 'Last issue/year',

  // Modals - used in multiple places in modal components
  'modal.publicBatch.confirmation': 'Vahvistus / Bekräftelse / Confirmation',
  'modal.publicBatch.confirmation.text.part1': 'Vahvistan edustavani kustantajaa ',
  'modal.publicBatch.confirmation.text.part2': ' ja omistavani kustantajatunnuksen ',
  'modal.publicBatch.confirmation.text.part3': 'Jag bekräftar att jag representerar förlaget ',
  'modal.publicBatch.confirmation.text.part4': ' och äger förlagsbeteckningen ',
  'modal.publicBatch.confirmation.text.part5': 'I confirm I represent ',
  'modal.publicBatch.confirmation.text.part6': ' (publisher ID {id})',

  // Service messages - used in action dispatchers (store/actions)
  'serviceMessage.registration.success': 'Registration request sent successfully',
  'serviceMessage.registration.error': 'Registration request failed',
  'serviceMessage.requestCreate.successfull': 'Request sent successfully',
  'serviceMessage.requestCreate.unsuccessfull': 'Request sending failed',
  'serviceMessage.requestQuery.unsuccessfull': 'Request query failed',
  'serviceMessage.requestRead.unsuccessfull': 'Request read failed',
  'serviceMessage.publisherRead.unsuccessfull': 'Publisher read failed',
  'serviceMessage.publisherSearch.unsuccessfull': 'Publisher search failed',
  'serviceMessage.batchRead.unsuccessfull': 'Batch read failed',
  'serviceMessage.batchQuery.unsuccessfull': 'Batches query failed',
  'serviceMessage.batchDownload.successfull': 'Downloaded successfully',
  'serviceMessage.batchDownload.unsuccessfull': 'Download failed',

  // Service messages - errors
  'serviceMessage.turnstileScript.error': 'An unknown error has occurred. Please refresh the page and try again.',

  // Turnstile info
  'form.turnstile.title': 'Important note',
  'form.turnstile.info': 'By proceeding to complete this form you agree and consent that the site is protected by an automated detection service to distinguish human users from bot users. In the process, the service provider (Cloudflare) receives information on your IP-address.',
  'form.turnstile.info.batchdownload': 'By proceeding to download the identifiers you agree and consent that the site is protected by an automated detection service to distinguish human users from bot users. In the process, the service provider (Cloudflare) receives information on your IP-address.',
  'form.turnstile.link.privacy': 'Cloudflare privacy policy',
  'form.turnstile.link.terms': 'Cloudflare terms of use',

  // Accessibility statement
  'accessibilityStatement.title': 'Accessibility statement',
  'accessibilityStatement.description.main': 'This accessibility statement on the identifier portal service was created on 9 May 2023 (with a subsequent update on 23 October 2023). The service is governed by the Act on the Provision of Digital Services (306/2019), which requires that public online services be accessible. The accessibility requirements indicated in the statement are listed in the official {link}.',
  'accessibilityStatement.description.main.link': 'Web Content Accessibility Guidelines (WCAG) version 2.1',
  'accessibilityStatement.description.secondary': 'We have assessed the accessibility of the service independently.',
  'accessibilityStatement.status.title': 'The accessibility status of the digital service',
  'accessibilityStatement.status.description': 'The service partly meets the accessibility requirements.',
  'accessibilityStatement.issues.title': 'Non-accessible content',
  'accessibilityStatement.issues.disclaimer': 'Disproportionate burden',
  'accessibilityStatement.issues.disclaimer.description': 'As the redesign of the service remains incomplete in some areas, deficiencies in its usability may occur. If the user cannot retrieve the desired information using the current user interface or submit applications related to identifiers, requests for information and applications can be sent to isbn-keskus@helsinki.fi.',
  'accessibilityStatement.issues.subTitle1': 'Inaccessible content and related deficiencies',
  'accessibilityStatement.issues.subTitle2': 'Accessibility criteria not met',
  'accessibilityStatement.issues.list.title': 'The website does not yet fully comply with all requirements.',
  'accessibilityStatement.issues.labels.title': 'Perceivable: Icon labels are deficient.',
  'accessibilityStatement.issues.labels.description': 'The label of the publication type icon in the list view of the publisher register is not visible to screen readers (aria-hidden). The labels of the footer’s social media icons are not sufficiently clear.',
  'accessibilityStatement.issues.labels.wcag': '1.1.1 Non-text Content',
  'accessibilityStatement.issues.semantics.title': 'Perceivable: Semantic purpose of elements',
  'accessibilityStatement.issues.semantics.description': 'The front page uses <br> elements that screen reader users hear as ‘empty group’. The table component of the publisher register lacks a semantic structure (caption, etc.).',
  'accessibilityStatement.issues.semantics.wcag': '1.3.1 Info and Relationships',
  'accessibilityStatement.issues.reflow.title': 'Perceivable: Scrolling in two dimensions',
  'accessibilityStatement.issues.reflow.description': 'Content is not entirely responsive when the page width is under 450 px (the target is 320px). This does not necessarily have a direct effect on functionality, but clearly affects usability and the accessibility of the service.',
  'accessibilityStatement.issues.reflow.wcag': '1.4.10 Reflow',
  'accessibilityStatement.issues.links.title': 'Operable: Unclear text alternatives in the language menu',
  'accessibilityStatement.issues.links.description': 'The text alternatives for links are unclear, screen reader users hear them as such - EN, FI, SV.',
  'accessibilityStatement.issues.links.wcag': '2.4.4 Link Purpose (In Context)',
  'accessibilityStatement.issues.siteMap.title': 'Operable: Missing site map',
  'accessibilityStatement.issues.siteMap.description': 'There is currently only one way to locate individual web pages, namely, the navigation menu.',
  'accessibilityStatement.issues.siteMap.wcag': '2.4.5 Multiple Ways',
  'accessibilityStatement.issues.titles.title': 'Operable: Heading levels incorrectly ordered',
  'accessibilityStatement.issues.titles.description': 'Some heading levels in the application form for ISBNs and ISMNs and the form for publisher registration are in the wrong order. These include the info box headings on the following pages: Additional organisational details (Publisher) and Basic organisational details, Publication details, Series details, Identifier type (ISBN/ISMN).',
  'accessibilityStatement.issues.titles.wcag': '2.4.6 Headings and Labels',
  'accessibilityStatement.issues.footer.title': 'Operable: Footer’s social medial labels in focus mode.',
  'accessibilityStatement.issues.footer.description': 'The focus status indicators of the footer’s social media labels are poorly visible.',
  'accessibilityStatement.issues.footer.wcag': '2.4.7 Focus Visible',
  'accessibilityStatement.issues.lang.title': 'Understandable: HTML lang attribute not updated',
  'accessibilityStatement.issues.lang.description': 'In some cases, the lang attribute in HTML is not updated according to the language of the user.',
  'accessibilityStatement.issues.lang.wcag': '3.1.1 Language of Page',
  'accessibilityStatement.issues.batch.title': 'Understandable: Lang attributes missing in the text of the info pop-up on the identifier list page',
  'accessibilityStatement.issues.batch.description': 'The info pop-up on individual identifier list pages contains text in three languages, each of which should be labelled separately with a lang attribute.',
  'accessibilityStatement.issues.batch.wcag': '3.1.2 Language of Parts',
  'accessibilityStatement.issues.required.title': 'Understandable: HTML required attributes missing',
  'accessibilityStatement.issues.required.description': 'Required fields in forms can be indicated using the required attribute in HTML. An explanation must also be added to the forms, for example ‘* – required fields’.',
  'accessibilityStatement.issues.required.wcag': '3.3.2 Labels or Instructions',
  'accessibilityStatement.feedback.title': 'Did you notice an accessibility issue in our digital service?',
  'accessibilityStatement.feedback.description': 'Tell us about it and we will do our best to rectify it.',
  'accessibilityStatement.feedback.contact.title': 'Email',
  'accessibilityStatement.feedback.contact.email': 'isbn-keskus@helsinki.fi',
  'accessibilityStatement.authority.title': 'Supervisory authority',
  'accessibilityStatement.authority.description': 'If you notice accessibility issues on the website, first leave your feedback with us, the administrators of the website. It may take up to 14 days to receive an answer. If you are not satisfied with the answer or do not receive an answer from us within two weeks, you may submit a complaint to the {link}. The Traficom website has detailed instructions on how to submit a complaint and how the issue will be handled.',
  'accessibilityStatement.authority.description.link': 'Digital Accessibility Supervision Unit of the Finnish Transport and Communications Agency Traficom',
  'accessibilityStatement.authority.contact.title': 'Contact information of the supervisory authority',
  'accessibilityStatement.authority.contact.organization': 'Finnish Transport and Communications Agency Traficom',
  'accessibilityStatement.authority.contact.department': 'Digital Accessibility Supervision Unit',
  'accessibilityStatement.authority.contact.website': 'www.saavutettavuusvaatimukset.fi',
  'accessibilityStatement.authority.contact.email': 'saavutettavuus(at)traficom.fi',
  'accessibilityStatement.authority.contact.phone': 'phone (switchboard) 029 534 5000',

  // Privacy policy
  'privacyPolicy.title': 'Privacy policy',
  'privacyPolicy.1a.title': '1a. Data file controller',
  'privacyPolicy.1a.content': 'The National Library of Finland\nLibrary network services\nP.O. Box 15 (Unioninkatu 36)\n00014 University of Helsinki\nTelephone 02941 911',
  'privacyPolicy.1b.title': '1b. Data protection officer',
  'privacyPolicy.1b.content': 'The National Library of Finland is an independent institute at the University of Helsinki. The data protection officer of the University of Helsinki can be reached by email at tietosuoja(at)helsinki.fi.',
  'privacyPolicy.2.title': '2. Contact information for questions about data processing',
  'privacyPolicy.2.content': 'isbn-keskus(at)helsinki.fi',
  'privacyPolicy.3.title': '3. Name of data file',
  'privacyPolicy.3.content': 'Identifier portal',
  'privacyPolicy.4.title': '4. Purpose and justification for processing personal data',
  'privacyPolicy.4.content': 'Personal data are processed to distinguish between individual customers and to identify users logged in to various services in the identifier portal. Personal data are also processed in the assignment process for IBSN, ISMN and ISSN identifiers for the unique identification of publishers and the maintenance of publisher registers. In addition, data are processed to investigate potential errors and misconduct. The personal data of users with administrator privileges are processed to verify system activity data.\n\nSince the publisher prefix included in ISBN identifiers identifies individual publishers, national and international registers are needed to maintain this information. The publisher register is primarily used as a tool by the Finnish national ISBN Agency to contact publishers or, in unclear cases, to determine which publisher has published a certain publication. The data are also available in international ISBN and ISMN registers.\n\nInformation (e.g., IP and URL addresses) on users logging in to the service will be temporarily stored for processing.\n\nThe grounds for the processing of personal data is the legitimate interest of the controller. One of the duties of the ISBN Agency as a national registry authority is to publish a database enabling searches for granted ISBN identifiers or publisher codes. This helps promote the use of the ISBN standard and makes it easier to find publishers and their books. For monitoring and managing the capacity of the ISBN system, the International ISBN Agency must also have up-to-date information on the assigned ISBN identifiers. The International ISBN Agency receives information on assigned identifiers from the national agencies.',

  'privacyPolicy.5.title': '5. Content of the data file',
  'privacyPolicy.5.prefix': 'For this purpose, we process the following personal data:',
  'privacyPolicy.5.publisherInformation': 'Basic publisher details',
  'privacyPolicy.5.publisherInformation.language': 'Language',
  'privacyPolicy.5.publisherInformation.name': 'Name',
  'privacyPolicy.5.publisherInformation.contactPersonInfo': 'Names, phone numbers and email addresses of contact persons',
  'privacyPolicy.5.publisherInformation.address': 'Address',
  'privacyPolicy.5.publisherInformation.otherNames': 'Previous names and other names of the publisher',
  'privacyPolicy.5.publisherInformation.publisherIdentifier': 'Publisher code(s)',
  'privacyPolicy.5.publisherInformation.additionalInformation': 'Information entered separately by the user in the field for additional information',
  'privacyPolicy.5.publisherInformation.publisherClassification': 'Publishing subject matter',
  'privacyPolicy.5.publicationInformation': 'Basic publication details',
  'privacyPolicy.5.publicationInformation.publisherName': 'Name of the publisher',
  'privacyPolicy.5.publicationInformation.publisherEmail': 'Email of the publisher',
  'privacyPolicy.5.publicationInformation.publisherAddress': 'Address details of the publisher',
  'privacyPolicy.5.publicationInformation.publisherContactPerson': 'Name of contact person for the publisher',
  'privacyPolicy.5.publicationInformation.publisherPhone': 'Phone number of the publisher',
  'privacyPolicy.5.publicationInformation.authorInformation': 'Names and roles of the authors',
  'privacyPolicy.5.superuserInformation': 'Basic superuser details ',
  'privacyPolicy.5.superuserInformation.name': 'Name',
  'privacyPolicy.5.superuserInformation.username': 'Username',
  'privacyPolicy.5.superuserInformation.password': 'Password',
  'privacyPolicy.5.superuserInformation.personalSettings': 'Personal user settings',
  'privacyPolicy.5.superuserInformation.email': 'Email',
  'privacyPolicy.5.personalization': 'Data collected for personalized services',
  'privacyPolicy.5.personalization.settings': 'Personal user settings (e.g., interface language selection)',
  'privacyPolicy.5.other': 'Other information',
  'privacyPolicy.5.other.mandatoryInfo': 'Information necessary for utilising the online service',
  'privacyPolicy.5.other.errorAndMisconductInfo': 'Information necessary for investigating errors and misconduct',
  'privacyPolicy.5.suffix': 'The National Library of Finland does not use the collected data for marketing purposes.',

  'privacyPolicy.6.title': '6. Regular sources of data',
  'privacyPolicy.6.content': 'The data in the data file are stored when publishers join the ISBN or ISMN system, or when applying for ISBN or ISMN identifiers on the basis of information entered by the user. Contact details are compiled from the information provided by the publishers.\n\nUsers independently store the data in the identifier portal. The data can also be stored in the data file by system administrators when users interact with the ISBN Agency or the ISSN Agency by email or phone. Data on journal publishers in the ISSN register are regularly supplemented by collecting information from public sources.\n\nData on operations carried out by system administrators are stored on the basis of the functions carried out by them.\n\nData on the use of personalised functions are stored by users.',
  'privacyPolicy.7.title': '7. Processing and protection of sensitive personal data',
  'privacyPolicy.7.content': 'No sensitive personal data are processed in the identifier portal.',
  'privacyPolicy.8.title': '8. Disclosure of data',
  'privacyPolicy.8.content': 'Every year, publisher data are sent to the Global Register of Publishers maintained by the International ISBN Agency. Every year, data on publishers of sheet music are sent to the International Music Publishers’ Database maintained by the International ISMN Agency. Limited publisher details (official name, street address, city, postal code, phone number and web address) are publicly available online in a publisher register maintained by the Finnish ISBN Agency.\n\nData related to publications (e.g., title, publication date, identifiers, publisher and authors) are forwarded to the Melinda metadata repository and the library system of the National Library of Finland, after which they will be publicly available. In the case of ISSN publications, the metadata will be forwarded separately to the ISSN International Centre.\n\nThe technical log data of the website’s communications are partially stored in the services provided by Cloudflare Inc, a contracting partner of the National Library. Cloudflare processes data in the European Economic Area (EEA) and the United States. The grounds for the transfer of personal data are standard contractual clauses approved by the European Commission.',
  'privacyPolicy.9.title': '9. Technical log data for the website and telecommunication',
  'privacyPolicy.9.content': 'Technical log data are collected on service users for the purposes of service provision and information security. Log data include information, such as time stamps, browser versions, operating systems and IP addresses, which can be used to connect individual users to natural persons. The above information is only used to investigate errors or information security incidents. The temporary storage of personal data included in the log data is necessary for service provision.\n\nThe National Library’s contracting partner Cloudflare Inc collects log data related to the services it provides in terms of the Cloudflare services used in the identifier portal. The data include information, such as time stamps and IP addresses, which can be used to connect individual users to natural persons.',
  'privacyPolicy.10.title': '10. Duration of personal data storage and removal of unnecessary personal dat',
  'privacyPolicy.10.content': 'Personal data processed in the assignment process for ISBN, ISMN and ISSN identifiers as well as personal data in publisher registers are stored in accordance with the specifications in their descriptions of data files. Data are stored permanently in the data file. Contact details can be changed or erased on request. The personal data of National Library employees will be erased one year after the termination of employment.',
  'privacyPolicy.11.title': '11. What rights do you have?',
  'privacyPolicy.11.part1.boldContent': 'Right to access and rectify personal data',
  'privacyPolicy.11.part1.content': 'You have the right to know whether the National Library of Finland is processing your personal data.\n\nYou have the right to know also which such personal details are being processed.\n\nIf you wish to know even more specifically which personal details are being processed, please write to isbn-keskus(at)helsinki.fi\n\n',
  'privacyPolicy.11.part2.boldContent': 'Right to lodge a complaint with a supervisory authority',
  'privacyPolicy.11.part2.content': 'You have the right to subject the legality of the University’s activities to a review by the Data Protection Ombudsman.\n\n',
  'privacyPolicy.11.part3.boldContent': 'Right to erasure',
  'privacyPolicy.11.part3.content': 'You have the right to request the erasure of your personal data by writing to isbn-keskus(at)helsinki.fi',
  'privacyPolicy.12.title': '12. Principles of data security',
  'privacyPolicy.12.content': 'The data are recorded exclusively in electronic format. Only system and other administrators, authenticated by personal usernames and passwords, may access protected data. Public information is accessible on the public web.',
  'privacyPolicy.13.title': '13. Transfer of data outside the EU or the European Economic Area',
  'privacyPolicy.13.content': 'Every year, publisher data are sent to the Global Register of Publishers maintained by the International ISBN Agency in London. Every year, data on publishers of sheet music are sent to the International Music Publishers’ Database maintained by the International ISMN Agency in Berlin. Limited publisher details (official name, street address, city, postal code, phone number, publisher codes and web address) are publicly available online in a publisher register maintained by the Finnish national ISBN Agency.\n\nIn the case of services provided by the National Library’s contracting partner Cloudflare, the necessary data can be transferred outside the EU or the EEA, as defined in section 9 (‘Technical log data for the website and telecommunications’).\n\nApart from the above-mentioned exceptions, data will not be transferred outside the European Union or the European Economic Area.',
  'privacyPolicy.14.title': '14. Automated decision-making and profiling',
  'privacyPolicy.14.content': 'The processing does not involve automated profiling on the basis of your personal data.'
};

export default en;
