/**
 *
 * @licstart  The following is the entire license notice for the JavaScript code in this file.
 *
 * Public UI service of Identifier Services system
 *
 * Copyright (C) 2023 University Of Helsinki (The National Library Of Finland)
 *
 * This file is part of identifier-services-ui-public
 *
 * identifier-services-ui-public program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * identifier-services-ui-public is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @licend  The above is the entire license notice
 * for the JavaScript code in this file.
 *
 */

const fi = {
  // Common translations - used in multiple components
  'common.isbn': 'ISBN',
  'common.ismn': 'ISMN',
  'common.isbn-ismn': 'ISBN ja ISMN',
  'common.issn': 'ISSN',
  'common.user': 'Käyttäjä',
  'common.users': 'Käyttäjät',
  'common.publisher.isbn': 'Kustantaja',
  'common.publishers.isbn': 'Kustantajat',
  'common.publisherDetails.isbn': 'Kustantajan tiedot',
  'common.publisher.issn': 'Julkaisija',
  'common.publishers.issn': 'Julkaisijat',
  'common.publisherDetails.issn': 'Julkaisijan tiedot',
  'common.request': 'Pyyntö',
  'common.requests': 'Pyynnöt',
  'common.requestDetails': 'Pyynnön tiedot',
  'common.publication': 'Julkaisu',
  'common.publications': 'Julkaisut',
  'common.publicationDetails': 'Julkaisun tiedot',
  'common.batch':  'Tunnuslista',
  'common.batches': 'Tunnuslistat',
  'common.batchDetails': 'Tunnuslistan tiedot',
  'common.yes': 'Kyllä',
  'common.no': 'Ei',
  'common.true': 'Kyllä',
  'common.true.allLangs': 'Kyllä / Ja / Yes',
  'common.false': 'Ei',
  'common.false.allLangs': 'Ei / Nej / No',
  'common.noData': 'Ei hakutuloksia',
  'common.blank': 'Tyhjä',
  'common.search.inputPlaceholder': 'Hae...',
  'common.search.searchById': 'Hae ID:llä...',
  'common.search.searchByPublisherName': 'Hae julkaisijan nimellä tai sähköpostiosoitteella...',
  'common.noValue': '-',
  'common.name': 'Nimi',
  'common.undefined': 'Ei määritelty',
  'common.link': 'Linkki',
  'common.identifier': 'Tunnus',
  'common.identifiers': 'Tunnukset',
  'common.identifiersPrinted': 'Tunnukset (painettu)',
  'common.identifiersElectronical': 'Tunnukset (elektroninen)',
  'common.amount': 'Lukumäärä',
  'common.status': 'Tila',
  'common.id': 'ID',
  'common.contactDetails': 'Yhteystiedot',
  'common.noLink': 'Ei ole generoitu vielä',
  'common.important.info': 'Tärkeä huomio!',
  'common.datePicker.helperText': 'Esim. 06/2023',
  'common.privacypolicy.title': 'Tietosuojaseloste',
  'common.other': 'muu',
  'common.errorPage': 'Virhesivu',
  'common.skipLink': 'Hyppää pääsisältöön',
  'common.inLibrary': 'Kansalliskirjastossa',
  'common.free': 'maksuttomia',
  'common.requiredField': 'Tähdellä (*) merkityt kohdat ovat pakollisia',
  // Numbers
  'common.one': 'Yksi',
  'common.two': 'Kaksi',
  'common.three': 'Kolme',
  'common.four': 'Neljä',
  // Publication languages
  'common.fin': 'suomi',
  'common.swe': 'ruotsi',
  'common.eng': 'englanti',
  'common.smi': 'saame',
  'common.fre': 'ranska',
  'common.ger': 'saksa',
  'common.rus': 'venäjä',
  'common.spa': 'espanja',
  'common.mul': 'muu/monikielinen',
  // Publisher's preferred languages
  'common.fi-FI': 'suomi',
  'common.en-GB': 'englanti',
  'common.sv-SE': 'ruotsi',
  // ISBN/ISMN publication types
  'common.BOOK': 'Kirja',
  'common.DISSERTATION': 'Väitöskirja',
  'common.MUSIC': 'Nuottijulkaisu',
  'common.SHEET_MUSIC': 'Nuottijulkaisu',
  'common.MAP': 'Kartta',
  'common.OTHER': 'Muu',
  // ISSN publication types
  'common.journal': 'Aikakauslehti (maksullinen)',
  'common.newsletter': 'Tiedotus- tai asiakaslehti',
  'common.staff_magazine': 'Henkilöstölehti',
  'common.membership_based_magazine': 'Jäsenlehti',
  'common.newspaper': 'Sanomalehti',
  'common.free_paper': 'Ilmaisjakelulehti',
  'common.monography_series': 'Erillisteossarja',
  'common.cartoon': 'Sarjakuva',
  'common.other_serial': 'Muu sarjajulkaisu (esim. tilasto, vuosikirja, raportti)',
  // ISSN publication frequency options
  'common.a': 'Kerran vuodessa',
  'common.f': 'Kaksi kertaa vuodessa',
  'common.q': 'Neljä kertaa vuodessa',
  'common.b': 'Kuusi kertaa vuodessa',
  'common.m': 'Kerran kuukaudessa',
  'common.w': 'Kerran viikossa',
  'common.d': 'Päivittäinen',
  'common.k': 'Päivitetään jatkuvasti',
  'common.#': 'Epäsäännöllinen',
  'common.z': 'Muu',
  // ISSN publication medium
  'common.printed': 'painettu',
  'common.online': 'sähköinen',
  'common.cdrom': 'CD-ROM',
  // Months
  'common.month.1': 'tammikuu',
  'common.month.2': 'helmikuu',
  'common.month.3': 'maaliskuu',
  'common.month.4': 'huhtikuu',
  'common.month.5': 'toukokuu',
  'common.month.6': 'kesäkuu',
  'common.month.7': 'heinäkuu',
  'common.month.8': 'elokuu',
  'common.month.9': 'syyskuu',
  'common.month.10': 'lokakuu',
  'common.month.11': 'marraskuu',
  'common.month.12': 'joulukuu',

  // Home page
  'homePage.title': 'Tunnistepalvelut',
  'homePage.description.part1': 'Kansainväliset standarditunnukset (ISBN, ISMN ja ISSN) identifioivat julkaisut yksiselitteisesti. Tunnuksia käytetään esim. kirja-alan jakeluketjuissa.',
  'homePage.description.part2': 'ISBN-tunnus identifioi kirjat, ISMN-tunnus nuottijulkaisut ja ISSN-tunnus jatkuvasti ilmestyvät julkaisut.',
  'homePage.description.part3': 'Suomessa tunnuksia haetaan Kansalliskirjastossa toimivista Suomen ISBN- ja ISSN-keskuksista. Tunnukset ovat maksuttomia.',
  'homePage.link': 'Lisätietoja {link}-tunnuksista',
  'homePage.instructions.title': 'Ohjeita ISBN-/ISMN-lomakkeiden täyttöön',
  'homePage.instructions.main.text': 'Jos kustannatte säännöllisesti (esim. yhden tai useamman julkaisun vuodessa) ettekä ole vielä liittynyt ISBN-järjestelmään, täyttäkää sekä liittymislomake ISBN-/ISMN-järjestelmään että ISBN-/ISMN-tunnuksen hakulomake.{lineBreak}{lineBreak}Jos kustannustoimintanne on satunnaista tai jos olette jo liittynyt ISBN-järjestelmään, täyttäkää vain ISBN-/ISMN-tunnuksen hakulomake.{lineBreak}{lineBreak}Kustantajan tiedot julkaistaan kansainvälisissä Global Register of Publishers ja/tai Music Publishers\' International ISMN Database -tietokannoissa ja tietoja käytetään myös Suomen ISBN-keskuksen toiminnassa ja/tai ne ovat haettavissa kustantajarekisteristä.',
  'homePage.instructions.isbn-ismn.text': 'ISBN identifioi julkiseen käyttöön tarkoitetut kirjat ja ISMN nuottijulkaisut. Suomen kansallinen ISBN-keskus vastaa ISBN- ja ISMN-tunnusten käytöstä Suomessa. Keskus ylläpitää kansallista kustantajarekisteriä ja välittää tietoja suomalaisista kustantajista kansalliseen ja kansainväliseen käyttöön.{lineBreak}{lineBreak}Tunnisteet metatiedon osana palvelevat koko julkaisualaa ja kirjastosektoria ja tukevat julkaisujen tunnistamista, käsittelyä ja löytyvyyttä. Tunnuksia käytetään mm. julkaisualan tilaus- ja jakelujärjestelmissä nopeuttamaan julkaisujen tunnistamista sekä kansainvälisissä että kansallisissa yhteisluetteloissa, bibliografioissa, kirjastojen lainausjärjestelmissä ja tiedonhauissa.{lineBreak}{lineBreak}Erillinen ISBN tai ISMN annetaan jokaiselle kirjalle tai nuottijulkaisulle, sen jokaiselle erilaiselle julkaisumuodolle (painettu, audiovisuaalinen, digitaalinen) ja muutoksia sisältävälle painokselle. Tunnukset edistävät julkaisujen tunnistamista julkaisualan jakeluketjussa ja takaavat, että asiakas saa käyttöönsä haluamansa julkaisun. Julkaisumuoto voi olla painettu kirja, audiovisuaalinen tai elektroninen tallenne.',
  'homePage.instructions.issn.text': 'ISSN-tunnus identifioi jatkuvasti ilmestyvät julkaisut, kuten lehdet ja sarjat. Suomen ISSN-keskus vastaa tunnusten jakamisesta Suomessa ja lähettää ISSN-tunnuksen saaneiden julkaisujen tiedot {link} -tietokantaan.{lineBreak}{lineBreak}ISSN-tunnus liittyy kiinteästi julkaisun nimeen, nimen muuttuessa myös tunnus on vaihdettava. Eri julkaisumuodoille annetaan erillinen ISSN-tunnus.',

  // Menu bar
  'menu.mobile': 'Valikko',
  'menu.home': 'Etusivu',
  'menu.publisherRegistry': 'Kustantajarekisteri',
  'menu.forms': 'Hakulomakkeet',
  'menu.forms.publisherRegistration': 'Liittymislomake ISBN-/ISMN-järjestelmään',
  'menu.forms.publicationRegistration': 'ISBN-/ISMN-hakulomakkeet',
  'menu.forms.issnPublicationRegistration': 'ISSN-hakulomake',
  'menu.forms.publicationRegistration.isbn-ismn': 'ISBN/ISMN kirjoille ja nuottijulkaisuille',
  'menu.forms.publicationRegistration.issn': 'ISSN sarjoille ja lehdille',
  'menu.forms.contactInformationChange': 'Yhteystietojen muutoslomake (ISBN/ISMN)',

  // Footer
  'footer.privacyPolicy': 'Tietosuoja',
  'footer.library': 'Kansalliskirjasto',
  'footer.address': 'PL 15 (Unioninkatu 36)',
  'footer.zip': '00014 Helsingin yliopisto',
  'footer.contact': 'Yhteystiedot',
  'footer.copyright': '© Kansalliskirjasto 2023',
  'footer.socials': 'Seuraa Kansalliskirjastoa',

  // Alt texts (Kuvatekstit)
  'altText.logo.library': 'Kansalliskirjaston virallinen logo',

  // Ranges (Tunnistelohkot)
  'ranges.identifierType': 'Lohkon tyyppi',

  // Error messages
  'error.field.required': 'Pakollinen kenttä',
  'error.format.issn': 'Annettu arvo ei ole kelvollinen ISSN-tunnus',
  'error.format.phone': 'Annettu puhelinnumero ei ole kelvollinen',
  'error.format.city': 'Annettu postitoimipaikka ei ole kelvollinen',
  'error.format.publishingActivityAmount': 'Max. pituus 5 merkkiä',
  'error.format.copies': 'Max. pituus 10 merkkiä',
  'error.format.maxLength': 'Syöttämäsi arvo on liian pitkä',
  'error.format.minLength': 'Syöttämäsi arvo on liian lyhyt',
  'error.format.integer': 'Merkitse tieto numeroina',
  'error.format.integer.twoDigits': 'Merkitse tieto kaksimerkkisenä numerona (esim. 39)',
  'error.format.year': 'Syötä arvo vuosilukuna (nelinumeroinen, esim. 1990)',
  'error.format.email': 'Annettu arvo ei ole kelvollinen sähköpostiosoite',
  'error.format.www': 'Merkitse tieto http:// tai https:// -alkuisena URL-osoitteena',
  'error.format.edition': 'Merkitse tieto numeroina (max. pituus 2 merkkiä)',
  'error.postalAddress.zip.format': 'Annettu postinumero ei ole kelvollinen',
  'error.postalAddress.city.format': 'Annettu postitoimipaikka ei ole kelvollinen',
  'error.publicationRegistrationIsbnIsmn.form.availability': 'ISBN-tunnus myönnetään vain julkiseen käyttöön tarkoitetulle julkaisulle',
  'error.publicationRegistrationIsbnIsmn.form.otherUniversitites': 'Kansalliskirjasto myöntää tunnuksia vain Helsingin yliopistolle tehdyille väitöskirjoille',
  'error.date.invalid': 'Annettu päivämäärä ei ole kelvollinen',
  'error.date.min': 'Päivämäärä ei voi olla nykyistä päivämäärää aikaisempi',
  'error.identifierBatch.invalid': 'Tunnuslistan hakeminen epäonnistui. Yrittäkää uudelleen tai ottakaa tarvittaessa yhteyttä asiakaspalveluun',
  'error.formEdit': 'Lomakkeessa on virheellisiä tietoja. Tarkistakaa seuraavat kentät:',
  'error.emptyField': ' ',
  'error.classification.maxAmount': 'Voit lisätä enintään 5 aihealuetta',

  // Error page texts
  'errorPage.header': 'Olemme pahoillamme, mutta jokin meni väärin',
  'errorPage.message.serviceDown': 'Näyttää siltä, että palvelin ei vastaa kutsuihin. Yrittäkää myöhemmin uudelleen. Tarvittaessa ottakaa yhteyttä asiakaspalveluun',
  'errorPage.message.serviceUnderMaintenance': 'Palvelin on huoltotilassa ja se on hetken poissa käytöstä. Yrittäkää myöhemmin uudelleen. Kiireellisissä asioissa ottakaa yhteyttä asiakaspalveluun',
  'errorPage.message.defaultError': 'Tuntematon virhe. Yrittäkää uudelleen tai ottakaa yhteyttä asiakaspalveluun',
  'errorPage.message.generatingMessageFailed': 'Viestipohjan hakeminen epäonnistui. Yrittäkää uudelleen tai ottakaa yhteyttä asiakaspalveluun',
  'errorPage.publicationRequestError': 'Sivun lataaminen epäonnistui. Tarkista osoite ja yritä uudelleen. Jos ongelma toistuu, ota yhteyttä ISBN-keskukseen',
  'errorPage.accessdenied.heading': 'Pääsy kielletty',
  'errorPage.accessdenied.message': 'Sinulla ei ole oikeuksia tälle sivulle.',
  'errorPage.admin.genericError': 'Järjestelmävirhe. Ole hyvä ja ota yhteyttä järjestelmäylläpitoon ongelman ratkaisemiseksi',

  // Common form translations - used in multiple forms
  'form.common.name': 'Kustantajan nimi',
  'form.common.otherNames': 'Muut nimet',
  'form.common.previousNames': 'Aikaisemmat nimet',
  'form.common.phone': 'Puhelinnumero',
  'form.common.email': 'Sähköposti',
  'form.common.contactPerson': 'Yhteyshenkilö',
  'form.common.website': 'Verkkosivu',
  'form.common.address': 'Lähiosoite',
  'form.common.addressLine1': 'Lisäosoiterivi',
  'form.common.zip': 'Postinumero',
  'form.common.city': 'Postitoimipaikka',
  'form.common.affiliates': 'Tytäryhtiöt',
  'form.common.affiliateOf': 'Emoyhtiöt',
  'form.common.distributors': 'Jakelijat',
  'form.common.distributorOf': 'Yritykset, joiden jakelija',
  'form.common.currentYear': 'Arvio julkaisumäärästä (tämä vuosi)',
  'form.common.nextYear': 'Arvio julkaisumäärästä (tuleva vuosi)',
  'form.common.classification': 'Luokitus',
  'form.common.classificationKeywords': 'Luokitusavainsanat',
  'form.common.classificationOther': 'Muu luokitus',
  'form.common.classificationCodes': 'Luokitustunnukset',
  'form.common.publisherIdentifier': 'Kustantajatunnus',
  'form.common.publisherIdentifiers': 'Kustantajatunnukset',
  'form.common.title': 'Nimeke',
  'form.common.subtitle': 'Alanimeke',
  'form.common.authorName': 'Tekijän nimi',
  'form.common.selectFormat': 'Julkaisu ilmestyy',
  'form.common.publicationMonth': 'Julkaisukuukausi',
  'form.common.publicationYear': 'Julkaisuvuosi',
  'form.common.language': 'Kieli',
  'form.common.identifier': 'Tunnus',
  'form.common.volume': 'Numero',
  'form.common.type': 'Tyyppi',
  'form.common.publishingActivities': 'Julkaisutoiminta',
  'form.common.instruction.multipleSelect': 'Voit valita useita vaihtoehtoja poimimalla ne alasvetovalikosta',
  'form.common.instruction.createableSelect': 'Lisätäksesi muita vaihtoehtoja, kirjoita haluamasi vaihtoehto kenttään ja valitse \'luo\' tai paina \'enter\'',
  'form.common.basicInfo': 'Perustiedot',
  'form.common.postalAddress': 'Postiosoite',
  'form.common.activeIdentifier': 'Aktiivinen {type}-kustantajatunnus',
  'form.common.organizationDetails': 'Organisaation lisätiedot',
  'form.common.frequency': 'Kustannusaktiivisuus',
  'form.common.activity': 'Aktiivisuus',
  'form.common.additionalDetails': 'Lisätiedot',
  'form.common.noAdditionalDetails': 'Ei lisätietoja',
  'form.common.createdAndUpdated': 'Luotu ja päivitetty',
  'form.common.created': 'Luotu',
  'form.common.createdBy': 'Luonut',
  'form.common.modified': 'Viimeksi päivitetty',
  'form.common.modifiedBy': 'Päivittänyt',
  'form.common.printFormat': 'Kansityyppi',
  'form.common.fileFormat': 'Tiedostomuoto',
  'form.common.subRangeType': 'Kustantajatunnuksen tyyppi',
  'form.common.otherInfo': 'Muut tiedot',
  'form.common.format': 'Julkaisumuoto',
  'form.common.publicationCity': 'Kustannuspaikka',
  'form.common.updated': 'Päivitetty',
  'form.common.confirmation': 'Vahvistustieto (vanha järjestelmä)',
  'form.common.scale': 'Mittakaava',
  'form.common.archiveRecord': 'Arkistotietue',
  'form.common.url': 'Verkko-osoite',

  // Form edition translations (Painos)
  'form.edition.first': 'Ensimmäinen',
  'form.edition.second': 'Toinen',
  'form.edition.third': 'Kolmas',
  'form.edition.fourth': 'Neljäs',
  'form.edition.fifth': 'Viides',
  'form.edition.sixth': 'Kuudes',
  'form.edition.seventh': 'Seitsemäs',
  'form.edition.eighth': 'Kahdeksas',
  'form.edition.ninth': 'Yhdeksäs',
  'form.edition.tenth': 'Kymmenes',
  'form.edition.eleventh': 'Yhdestoista',
  'form.edition.twelfth': 'Kahdestoista',
  'form.edition.thirteenth': 'Kolmastoista',
  'form.edition.fourteenth': 'Neljästoista',
  'form.edition.fifteenth': 'Viidestoista',

  // Printed publication format (Kansityyppi)
  'form.printFormat.paperback': 'Pehmeäkantinen',
  'form.printFormat.hardback': 'Kovakantinen',
  'form.printFormat.spiral_binding': 'Kierreselkä',
  'form.printFormat.other_print': 'Muu (painettu)',

  // File format (Tiedostomuoto)
  'form.fileFormat.pdf': 'PDF',
  'form.fileFormat.epub': 'EPUB',
  'form.fileFormat.cd_rom': 'CD-ROM',
  'form.fileFormat.mp3': 'MP3',
  'form.fileFormat.other': 'Muu (elektroninen)',

  // Frequency (Julkaisutiheys)
  'form.frequency.yearly': 'Kerran vuodessa',
  'form.frequency.biyearly': 'Kaksi kertaa vuodessa',
  'form.frequency.quarterly': 'Neljä kertaa vuodessa',
  'form.frequency.bimonthly': 'Kuusi kertaa vuodessa',
  'form.frequency.monthly': 'Kerran kuukaudessa',
  'form.frequency.weekly': 'Kerran viikossa',
  'form.frequency.daily': 'Päivittäinen',
  'form.frequency.continuously': 'Päivitetään jatkuvasti',
  'form.frequency.irregular': 'Epäsäännöllinen',
  'form.frequency.other': 'Muu',

  // Button labels
  'form.button.label.back': 'Takaisin',
  'form.button.label.next': 'Seuraava',
  'form.button.label.submit': 'Lähetä',
  'form.button.label.proceed': 'Jatka',
  'form.button.label.add': 'Lisää',
  'form.button.label.delete': 'Poista',
  'form.button.label.downloadAsTextfile': 'Lataa tekstitiedostona',
  'form.button.label.showIdentifiers': 'Näytä tunnukset',
  'form.button.label.identifiers': 'Tunnukset',

  // Publisher registration form (Kustantajan liittymislomake)
  'form.publisherRegistration.instructions.title': 'Kun kustantaja liittyy ISBN-järjestelmään, kustantaja sitoutuu samalla seuraaviin velvoitteisiin:',
  'form.publisherRegistration.instructions.note0': 'Kustantajan tulee käyttää ISBN-tunnuksia julkaisuissaan.',
  'form.publisherRegistration.instructions.note1.part1': 'ISBN-tunnus painetaan julkaisuihin ',
  'form.publisherRegistration.instructions.note1.link': 'ISBN-keskuksen kotisivuilla',
  'form.publisherRegistration.instructions.note1.part2': ' annettujen ohjeiden mukaisesti.',
  'form.publisherRegistration.instructions.note2': 'Kustantaja pitää yllä listausta ISBN-tunnuksen saaneista julkaisuistaan.',
  'form.publisherRegistration.instructions.note3': 'Kustantaja lähettää yhden kappaleen (ISBN-kustantajakappale) kustantamistaan julkaisuista heti niiden ilmestyttyä Suomen ISBN-keskukseen.',
  'form.publisherRegistration.instructions.note4': 'Kustantajan tiedot julkaistaan kansainvälisissä Global Register of Publishers ja/tai Music Publishers\' International ISMN Database -tietokannoissa. Tietoja käytetään myös Suomen ISBN-keskuksen toiminnassa ja ne ovat esillä ISBN-keskuksen kotisivulla.',
  'form.publisherRegistration.title': 'Kustantajan rekisteröinti',
  'form.publisherRegistration.stepper.label.basicInformation': 'Kustantajan tiedot',
  'form.publisherRegistration.stepper.label.publishingActivities': 'Kustannustoiminta',
  'form.publisherRegistration.stepper.label.organizationDetails': 'Organisaation lisätiedot',
  'form.publisherRegistration.stepper.label.preview': 'Esikatselu',
  'form.publisherRegistration.basicInformation.name': 'Kustantajan nimi*',
  'form.publisherRegistration.basicInformation.address': 'Lähiosoite*',
  'form.publisherRegistration.basicInformation.city': 'Postitoimipakka*',
  'form.publisherRegistration.basicInformation.zip': 'Postinumero*',
  'form.publisherRegistration.basicInformation.phone': 'Puhelinnumero*',
  'form.publisherRegistration.basicInformation.publisherEmail': 'Sähköpostiosoite*',
  'form.publisherRegistration.basicInformation.website': 'Kustantajan verkkosivun osoite',
  'form.publisherRegistration.basicInformation.contactPerson': 'Yhteyshenkilön nimi*',
  'form.publisherRegistration.basicInformation.email': 'Yhteyshenkilön sähköpostiosoite*',
  'form.publisherRegistration.basicInformation.otherNames': 'Muut nimimuodot',
  'form.publisherRegistration.publishingActivities.currentYear': 'Kuinka monta julkaisua kustannatte kuluvana vuonna?*',
  'form.publisherRegistration.publishingActivities.nextYear': 'Arvionne kustannusmäärästä ensi vuoden osalta?*',
  'form.publisherRegistration.publishingActivities.classification': 'Luokitustunnukset*',
  'form.publisherRegistration.publishingActivities.classification.placeholder': 'Valitse kustannustoiminnan aihealueet*',
  'form.publisherRegistration.publishingActivities.classificationOther': 'Jos et löydä sopivia aihealueita valikosta, lisää haluamasi tähän',
  'form.publisherRegistration.organization.affiliates': 'Tytäryhtiöt',
  'form.publisherRegistration.organization.affiliateOf': 'Emoyhtiö',
  'form.publisherRegistration.organization.distributors': 'Jakelijat',
  'form.publisherRegistration.organization.distributorOf': 'Yhtiöt joiden jakaja tai edustaja',
  'form.publisherRegistration.classification.general': 'Yleistä',
  'form.publisherRegistration.classification.book-business-lib': 'Kirja-ala. Kirjastotoimi',
  'form.publisherRegistration.classification.text-books': 'Oppikirjat',
  'form.publisherRegistration.classification.children-book': 'Lasten ja nuorten kirjat',
  'form.publisherRegistration.classification.official-publication': 'Virallisjulkaisut',
  'form.publisherRegistration.classification.university-publication': 'Korkeakoulujen ja yliopistojen julkaisut',
  'form.publisherRegistration.classification.electronic-publication': 'Elektroniset julkaisut',
  'form.publisherRegistration.classification.audiovisual': 'Audiovisuaalinen aineisto. Videot',
  'form.publisherRegistration.classification.philosophy': 'Filosofia',
  'form.publisherRegistration.classification.psychology': 'Psykologia',
  'form.publisherRegistration.classification.paranormal': 'Paranormaalit ilmiöt. Okkultismi. Astrologia',
  'form.publisherRegistration.classification.religion': 'Uskonto. Teologia',
  'form.publisherRegistration.classification.christianity': 'Kristinusko',
  'form.publisherRegistration.classification.orthodox': 'Ortodoksinen kirkko',
  'form.publisherRegistration.classification.other-religions': 'Muut uskonnot',
  'form.publisherRegistration.classification.social-science': 'Yhteiskuntatieteet. Sosiologia',
  'form.publisherRegistration.classification.political-studies': 'Poliittinen tutkimus. Kansainvälinen politiikka',
  'form.publisherRegistration.classification.military': 'Sotatiede',
  'form.publisherRegistration.classification.sociology': 'Sosiologia',
  'form.publisherRegistration.classification.economics': 'Taloustieteet',
  'form.publisherRegistration.classification.law': 'Oikeus',
  'form.publisherRegistration.classification.public-administration': 'Julkinen hallinto',
  'form.publisherRegistration.classification.education': 'Kasvatus. Opetus. Koulutus',
  'form.publisherRegistration.classification.ethnography': 'Perinnetieteet',
  'form.publisherRegistration.classification.local-history': 'Kotiseutututkimus',
  'form.publisherRegistration.classification.social-politics': 'Sosiaalipolitiikka. Sosiaalihuolto',
  'form.publisherRegistration.classification.mass-media': 'Joukkotiedotus. Media',
  'form.publisherRegistration.classification.literature': 'Kirjallisuudentutkimus',
  'form.publisherRegistration.classification.fiction': 'Kaunokirjallisuus',
  'form.publisherRegistration.classification.poetry': 'Runous',
  'form.publisherRegistration.classification.cartoons': 'Sarjakuvat',
  'form.publisherRegistration.classification.science-fiction': 'Science Fiction',
  'form.publisherRegistration.classification.crime-fiction': 'Rikosromaanit',
  'form.publisherRegistration.classification.linguistic': 'Kielitiede',
  'form.publisherRegistration.classification.sexual-minorities': 'Seksuaaliset vähemmistöt',
  'form.publisherRegistration.classification.minorities': 'Vähemmistöt',
  'form.publisherRegistration.classification.science': 'Luonnontieteet',
  'form.publisherRegistration.classification.mathematics': 'Matematiikka. Tilastotiede',
  'form.publisherRegistration.classification.astronomy': 'Tähtitiede',
  'form.publisherRegistration.classification.physics': 'Fysiikka',
  'form.publisherRegistration.classification.chemistry': 'Kemia',
  'form.publisherRegistration.classification.geology': 'Geologia',
  'form.publisherRegistration.classification.biology': 'Biologia',
  'form.publisherRegistration.classification.zoology': 'Eläintiede',
  'form.publisherRegistration.classification.botany': 'Kasvitiede',
  'form.publisherRegistration.classification.environmental-studies': 'Ympäristötieteet. Ympäristönsuojelu',
  'form.publisherRegistration.classification.technology': 'Teknologia',
  'form.publisherRegistration.classification.engineering': 'Insinööritieteet. Tekniikka',
  'form.publisherRegistration.classification.industry': 'Teollisuuden alat',
  'form.publisherRegistration.classification.construction': 'Rakentaminen',
  'form.publisherRegistration.classification.transport': 'Liikenne. Posti',
  'form.publisherRegistration.classification.information-tech': 'Tietotekniikka. Viestintätekniikka',
  'form.publisherRegistration.classification.medicine': 'Lääketiede. Psykiatria',
  'form.publisherRegistration.classification.odontology': 'Hammaslääketiede',
  'form.publisherRegistration.classification.veteriniry': 'Eläinlääketiede',
  'form.publisherRegistration.classification.pharmacology': 'Farmasia. Homeopatia',
  'form.publisherRegistration.classification.forestry': 'Metsätalous. Metsänhoito',
  'form.publisherRegistration.classification.agriculture': 'Maatalous',
  'form.publisherRegistration.classification.handicraft': 'Käsi- ja kotiteollisuus',
  'form.publisherRegistration.classification.art': 'Taide',
  'form.publisherRegistration.classification.performing-art': 'Esittävät taiteet',
  'form.publisherRegistration.classification.theatre': 'Teatteri. Elokuva',
  'form.publisherRegistration.classification.dance': 'Tanssi',
  'form.publisherRegistration.classification.visual-art': 'Kuvataiteet',
  'form.publisherRegistration.classification.art-history': 'Taidehistoria',
  'form.publisherRegistration.classification.architecture': 'Arkkitehtuuri. Taideteollisuus',
  'form.publisherRegistration.classification.fashion': 'Muoti',
  'form.publisherRegistration.classification.music': 'Musiikki',
  'form.publisherRegistration.classification.antique': 'Antiikki. Keräily',
  'form.publisherRegistration.classification.city-regional': 'Kaupunki- ja aluesuunnittelu',
  'form.publisherRegistration.classification.leisure-hobbies': 'Huvit ja harrastukset',
  'form.publisherRegistration.classification.sports': 'Urheilu',
  'form.publisherRegistration.classification.games': 'Pelit',
  'form.publisherRegistration.classification.hunting-fishing': 'Metsästys ja kalastus',
  'form.publisherRegistration.classification.gardening': 'Puutarhanhoito',
  'form.publisherRegistration.classification.home-economic': 'Kotitalous',
  'form.publisherRegistration.classification.health-beauty': 'Kauneus ja terveys',
  'form.publisherRegistration.classification.photography': 'Valokuvaus',
  'form.publisherRegistration.classification.tourism': 'Matkailu',
  'form.publisherRegistration.classification.humour': 'Huumori',
  'form.publisherRegistration.classification.history': 'Historia',
  'form.publisherRegistration.classification.geography': 'Maantiede',
  'form.publisherRegistration.classification.map-atlases': 'Kartat ja kartastot',
  'form.publisherRegistration.classification.archeology': 'Arkeologia',
  'form.publisherRegistration.classification.genealogy': 'Sukututkimus',
  'form.publisherRegistration.classification.numismatics': 'Numismatiikka',
  'form.publisherRegistration.preview.publishingFrequency': 'Julkaisutiheys',
  'form.publisherRegistration.preview.organizationDetails': 'Organisaation lisätiedot',
  'form.publisherRegistration.preview.postalAddress': 'Postiosoite',
  'form.publisherRegistration.preview.publisherInformation': 'Kustantajan tiedot',
  'form.publisherRegistration.card.affiliates': 'Onko yhtiöllänne/yhteisöllänne kustannustoimintaa harjoittavia alaosastoja tai tytäryhtiöitä Suomessa tai ulkomailla? Pyydämme ilmoittamaan yhtiöiden nimet ja osoitteet sekä arvion vuosittaisista kustannusmääristä.',
  'form.publisherRegistration.card.distributors': 'Oletteko ulkomaisen tai Suomessa kustantavan yhtiön/yhteisön yksinomainen jakaja tai edustaja? Ilmoittakaa yhtiön nimi ja osoite.',

  // ISBN/ISMN-form
  'form.isbnIsmn.title': 'ISBN- ja ISMN-tunnuksen hakulomake',
  'form.isbnIsmn.stepper.label.availabilityInformation': 'Perustiedot',
  'form.isbnIsmn.stepper.label.publisherBasicInfo': 'Kustantajan tiedot',
  'form.isbnIsmn.stepper.label.publishingActivities': 'Kustannustoiminta',
  'form.isbnIsmn.stepper.label.basicInformation': 'Julkaisun tiedot',
  'form.isbnIsmn.stepper.label.authorInformation': 'Tekijät',
  'form.isbnIsmn.stepper.label.seriesInformation': 'Sarjan tiedot',
  'form.isbnIsmn.stepper.label.formatBasic': 'Julkaisumuoto',
  'form.isbnIsmn.stepper.label.additionalDetails': 'Lisätietoja',
  'form.isbnIsmn.stepper.label.dissertationFormat': 'Väitöskirjan julkaisumuoto',
  'form.isbnIsmn.stepper.label.contactInfo': 'Yhteystiedot',
  'form.isbnIsmn.stepper.label.universityInformation': 'Yliopiston tiedot',
  'form.isbnIsmn.stepper.label.preview': 'Esikatselu',
  'form.isbnIsmn.availability.publicationsPublic': 'Onko julkaisu tarkoitettu julkiseen käyttöön, esim. lainattavaksi kirjastosta, myytäväksi kirjakaupassa, tai onko se mahdollisesti muulla tavoin julkisesti saatavilla? Jos kyseessä on verkkojulkaisu tai e-kirja, niin onko se vapaasti verkossa saatavilla tai tilattavissa esim. lukulaitteelle?*',
  'form.isbnIsmn.availability.type': 'Julkaisu on*',
  'form.isbnIsmn.availability.type.option.book': 'Kirja/kirjanen',
  'form.isbnIsmn.availability.type.option.dissertation': 'Väitöskirja',
  'form.isbnIsmn.availability.type.option.sheet_music': 'Nuottijulkaisu',
  'form.isbnIsmn.availability.type.option.map': 'Kartta',
  'form.isbnIsmn.availability.type.option.other': 'Muu',
  'form.isbnIsmn.availability.publicationsPublic.label': 'Onko julkaisunne julkisesti saatavilla?',
  'form.isbnIsmn.availability.type.label': 'Julkaisun tyyppi',
  'form.isbnIsmn.publisherInfo.name': 'Kustantajan nimi*',
  'form.isbnIsmn.publisherInfo.publisherIdentifierStr': 'Kustantajatunnus',
  'form.isbnIsmn.publisherInfo.address': 'Lähiosoite*',
  'form.isbnIsmn.publisherInfo.zip': 'Postinumero*',
  'form.isbnIsmn.publisherInfo.city': 'Postitoimipaikka*',
  'form.isbnIsmn.publisherInfo.phone': 'Puhelinnumero*',
  'form.isbnIsmn.publisherInfo.contactPerson': 'Yhteyshenkilön nimi*',
  'form.isbnIsmn.publisherInfo.email': 'Sähköpostiosoite*',
  'form.isbnIsmn.publishingActivities.hasPublishedBefore': 'Oletteko kustantaneet aikaisemmin?',
  'form.isbnIsmn.publishingActivities.occasionalOrContinuous': 'Onko kustannustoimintanne?*',
  'form.isbnIsmn.publishingActivities.thisYear': 'Kuinka monta julkaisua kustannatte vuosittain?',
  'form.isbnIsmn.publishingActivities.option.occasional': 'Satunnaista',
  'form.isbnIsmn.publishingActivities.option.continuous': 'Jatkuvaa',
  'form.isbnIsmn.university.isHelsinki': 'Onko väitöskirja tehty Helsingin yliopistolle?',
  'form.isbnIsmn.university.contactInfo.contactPerson': 'Yhteyshenkilön nimi*',
  'form.isbnIsmn.university.contactInfo.address': 'Lähiosoite*',
  'form.isbnIsmn.university.contactInfo.zip': 'Postinumero*',
  'form.isbnIsmn.university.contactInfo.city': 'Postitoimipaikka*',
  'form.isbnIsmn.university.contactInfo.phone': 'Puhelinnumero*',
  'form.isbnIsmn.university.contactInfo.email': 'Sähköpostiosoite*',
  'form.isbnIsmn.publicationInfo.title': 'Nimeke*',
  'form.isbnIsmn.publicationInfo.subtitle': 'Alanimeke',
  'form.isbnIsmn.publicationInfo.language': 'Valitse kieli*',
  'form.isbnIsmn.publicationInfo.scale': 'Mittakaava',
  'form.isbnIsmn.publicationInfo.publicationMonth': 'Julkaisukuukausi*',
  'form.isbnIsmn.publicationInfo.publicationYear': 'Julkaisuvuosi*',
  'form.isbnIsmn.authors.givenName': 'Etunimi*',
  'form.isbnIsmn.authors.familyName': 'Sukunimi*',
  'form.isbnIsmn.authors.role': 'Rooli*',
  'form.isbnIsmn.authors.role.option.author': 'Tekijä',
  'form.isbnIsmn.authors.role.option.illustrator': 'Kuvittaja',
  'form.isbnIsmn.authors.role.option.translator': 'Kääntäjä',
  'form.isbnIsmn.authors.role.option.editor': 'Toimittaja',
  'form.isbnIsmn.authors.card.name': 'Nimi:',
  'form.isbnIsmn.authors.card.roles': 'Roolit:',
  'form.isbnIsmn.authors.card.noAuthors': 'Tekijöitä ei ole lisätty vielä, lisää tekijä täyttämällä tiedot ja painamalla \'Lisää\' -painiketta',
  'form.isbnIsmn.authors.card.addMoreAuthors': 'Lisää muita tekijöitä täyttämällä tiedot ja painamalla \'Lisää\' -painiketta. Voit lisätä enintään neljä tekijää. Loput tekijät huomioidaan teoksen saapuessa Kansalliskirjastoon.',
  'form.isbnIsmn.authors.card.maxAuthors': 'Voit lisätä enintään neljä tekijää. Loput tekijät huomioidaan teoksen saapuessa Kansalliskirjastoon.',
  'form.isbnIsmn.series.title': 'Sarjan nimi',
  'form.isbnIsmn.series.volume': 'Osan numero',
  'form.isbnIsmn.format.label': 'Julkaisu ilmestyy*',
  'form.isbnIsmn.format.option.print': 'Painettuna',
  'form.isbnIsmn.format.option.electronical': 'Sähköisenä',
  'form.isbnIsmn.format.option.print_electronical': 'Sekä painettuna että sähköisenä',
  'form.isbnIsmn.format.dissertation.option.printed': 'Painettuna (pehmeäkantinen)',
  'form.isbnIsmn.format.dissertation.option.electronic': 'Sähköisenä (PDF)',
  'form.isbnIsmn.format.dissertation.option.both': 'Sekä painettuna (pehmeäkantinen) että sähköisenä (PDF)',
  'form.isbnIsmn.format.dissertation.option.printed.edition': 'Monesko painos',
  'form.isbnIsmn.format.dissertation.option.printed.manufacturer': 'Kirjapaino tai muu valmistaja',
  'form.isbnIsmn.format.dissertation.option.printed.city': 'Valmistajan kotipaikka',
  'form.isbnIsmn.format.printFormat': 'Kansityyppi*',
  'form.isbnIsmn.format.printFormat.other': 'Jos muu kansityyppi, mikä?*',
  'form.isbnIsmn.format.printFormat.printed.manufacturer': 'Kirjapaino tai muu valmistaja',
  'form.isbnIsmn.format.printFormat.printed.city': 'Valmistajan kotipaikka',
  'form.isbnIsmn.format.printFormat.printed.edition': 'Monesko painos',
  'form.isbnIsmn.format.printFormat.printed.copies': 'Painoksen suuruus',
  'form.isbnIsmn.format.fileFormat': 'Tiedostomuoto*',
  'form.isbnIsmn.format.fileFormat.other': 'Jos muu tiedostomuoto, mikä?*',
  'form.isbnIsmn.additionalDetails': 'Lisätiedot',
  'form.isbnIsmn.preview.publisherDetails': 'Kustantajan tiedot',
  'form.isbnIsmn.preview.publicationInfo': 'Julkaisun tiedot',
  'form.isbnIsmn.preview.universityName': 'Yliopisto',
  'form.isbnIsmn.preview.helsinki': 'Helsingin yliopisto',
  'form.isbnIsmn.preview.previouslyPublished': 'Kustantanut aiemmin',
  'form.isbnIsmn.preview.thisYear': 'Kuinka monta julkaisua kustannatte vuosittain',
  'form.isbnIsmn.preview.format': 'Julkaisu ilmestyy',
  'form.isbnIsmn.preview.formatDetails': 'Julkaisumuoto',
  'form.isbnIsmn.preview.printFormat': 'Kansityyppi',
  'form.isbnIsmn.preview.printFormatOther': 'Muut kansityypit',
  'form.isbnIsmn.preview.fileFormat': 'Tiedostomuoto',
  'form.isbnIsmn.preview.fileformatOther': 'Muut tiedostomuodot',
  'form.isbnIsmn.preview.authors': 'Tekijät',
  'form.isbnIsmn.preview.additionalDetails': 'Lisätiedot',
  'form.isbnIsmn.preview.manufacturer': 'Kirjapaino',
  'form.isbnIsmn.preview.city': 'Valmistajan kotipaikka',
  'form.isbnIsmn.preview.edition': 'Painos',
  'form.isbnIsmn.preview.run': 'Painoksen suuruus',
  'form.isbnIsmn.preview.seriesDetails': 'Sarjan tiedot',
  'form.isbnIsmn.preview.publicationDetails': 'Julkaisun lisätiedot',
  'form.isbnIsmn.preview.isPublic': 'Julkinen',
  'form.isbnIsmn.card.universityOfHelsinki': 'Ennen kun täytät ISBN-hakemuksen, tarkista saatko ISBN-tunnuksen omalta laitokselta/tiedekunnasta.',
  'form.isbnIsmn.card.otherUniversity': 'Tarkista saatko ISBN-tunnuksen omalta laitokselta/yliopistolta. Jos väittelet muualla kuin Helsingin yliopistossa, pyydä ISBN-tunnus omalta laitokselta/tiedekunnasta. Tarvittaessa ota yhteyttä ISBN-keskukseen.',
  'form.isbnIsmn.card.publicationIsPublic': 'Huomaathan, että ISBN-tunnus myönnetään vain julkiseen käyttöön tarkoitetulle julkaisulle. Jos julkaisu on tarkoitettu ainoastaan sisäiseen käyttöön, esim. ystäville, sukulaisille tai jonkun yhteisön sisäiseen käyttöön, älä hae ISBN-tunnusta. ',
  'form.isbnIsmn.card.editionInfo': 'Jos haet tunnusta uudelle painokselle',
  'form.isbnIsmn.card.publicationInfo': 'Tunnusta ei voi hakea jälkikäteen, jos kirja on jo painettu tai julkaistu verkossa.',
  'form.isbnIsmn.card.seriesInfo': 'Täytä sarjan tiedot mikäli julkaisu ilmestyy sarjassa.',

  // ISSN-form
  'form.issn.title': 'ISSN-hakulomake',
  'form.issn.stepper.label.publisherInformation': 'Julkaisijan tiedot',
  'form.issn.stepper.label.publicationInformation_1': '1. julkaisun tiedot',
  'form.issn.stepper.label.publicationInformation_2': '2. julkaisun tiedot',
  'form.issn.stepper.label.publicationInformation_3': '3. julkaisun tiedot',
  'form.issn.stepper.label.publicationInformation_4': '4. julkaisun tiedot',
  'form.issn.stepper.label.publicationVersions': 'Julkaisujen lukumäärä',
  'form.issn.stepper.label.publicationVersionsCheck': 'Muut versiot (tarkistus)',
  'form.issn.stepper.label.preview': 'Esikatselu',
  'form.issn.versionInfo.number_of_versions': 'Julkaisujen lukumäärä',
  'form.issn.publisherInfo.name': 'Julkaisijan nimi*',
  'form.issn.publisherInfo.contact_person': 'Yhteyshenkilö*',
  'form.issn.publisherInfo.email': 'Sähköpostiosoite*',
  'form.issn.publisherInfo.phone': 'Puhelinnumero*',
  'form.issn.publisherInfo.address': 'Lähiosoite*',
  'form.issn.publisherInfo.zip': 'Postinumero*',
  'form.issn.publisherInfo.city': 'Postitoimipaikka*',
  'form.issn.publicationInfo.title': 'Julkaisun nimeke*',
  'form.issn.publicationInfo.title.instructions': 'ISSN-tunnus liittyy kiinteästi julkaisun nimeen. Nimen tulee olla pysyvä ja se on painettava näkyviin julkaisuun.',
  'form.issn.publicationInfo.subtitle': 'Julkaisun alanimeke',
  'form.issn.publicationInfo.place_of_publication': 'Kustannuspaikka*',
  'form.issn.publicationInfo.printer': 'Kirjapaino',
  'form.issn.publicationInfo.issued_from_year': 'Ilmestynyt alkaen (vuosi)*',
  'form.issn.publicationInfo.issued_from_number': 'Ilmestynyt alkaen (numero)*',
  'form.issn.publicationInfo.frequency': 'Ilmestymistiheys*',
  'form.issn.publicationInfo.language': 'Julkaisun kieli*',
  'form.issn.publicationInfo.publication_type': 'Julkaisutyyppi*',
  'form.issn.publicationInfo.other': 'muu, mikä? *',
  'form.issn.publicationInfo.medium': 'Julkaisumuoto*',
  'form.issn.publicationInfo.url': 'Julkaisun www-osoite*',
  'form.issn.publicationInfo.previous': 'Julkaisun aiempi nimeke*',
  'form.issn.publicationInfo.issn': 'Julkaisun aiempi ISSN',
  'form.issn.publicationInfo.last_issue': 'Viimeinen tällä nimellä ilmestynyt numero/vuosi*',
  'form.issn.publicationInfo.main_series': 'Pääsarjan nimi*',
  'form.issn.publicationInfo.main_series_issn': 'Pääsarjan ISSN',
  'form.issn.publicationInfo.subseries': 'Alasarjan nimi*',
  'form.issn.publicationInfo.subseries_issn': 'Alasarjan ISSN',
  'form.issn.publicationInfo.another_medium': 'Julkaisun nimi*',
  'form.issn.publicationInfo.another_medium_issn': 'Julkaisun ISSN',
  'form.issn.publicationInfo.additional_info': 'Lisätietoja',
  'form.issn.publicationInfo.publication_was_issued': 'Onko julkaisu ilmestynyt aiemmin toisella nimellä?',
  'form.issn.publicationInfo.publication_has_main_series': 'Sisältyykö julkaisu johonkin pääsarjaan?',
  'form.issn.publicationInfo.publication_has_subseries': 'Onko julkaisulla alasarja/suplementti?',
  'form.issn.publicationInfo.publication_has_another_medium': 'Onko julkaisulla toinen julkaisumuoto?',
  'form.issn.publicationInfo.publication_has_another_medium.instructions': 'Jos sama julkaisu on aiemmin ilmestynyt eri julkaisumuodossa, merkitse sen tiedot tähän.',
  'form.issn.publicationInfo.instructions.part1': 'Julkaisun toiset julkaisumuodot',
  'form.issn.publicationInfo.instructions.part2': 'Jos sama julkaisu ilmestyy säännöllisesti myös jonakin muuna julkaisumuotona (painettuna, verkkojulkaisuna), saa tuo toinenkin julkaisumuoto oman ISSN-tunnuksen. Lisää jokaisen julkaisumuodon tiedot erikseen valitsemalla sopiva julkaisujen lukumäärä.{lineBreak}{lineBreak}',
  'form.issn.publicationInfo.instructions.part3': 'Julkaisun toiset kieliversiot',
  'form.issn.publicationInfo.instructions.part4': 'Jos sama julkaisu ilmestyy kokonaisuudessaan useammalla kielellä, saa jokainen kieliversio oman ISSN-tunnuksen. Kieliversiolla pitää olla oma numerointi. Lisää jokaisen kieliversion tiedot erikseen valitsemalla sopiva julkaisujen lukumäärä.',
  'form.issn.publicationInfo.instructions.part5': 'Julkaisujen enimmäismäärä',
  'form.issn.publicationInfo.instructions.part6': 'Yhdellä ISSN-hakulomakkeella voidaan hakea ISSN-tunnusta enintään neljälle julkaisulle. Mikäli tarvitset tunnuksen useammalle julkaisulle, ota yhteyttä ISSN-keskukseen.',
  'form.issn.publicationInfo.instructions.part7': '{icon} Hae verkkoversiolle tunnus vasta kun julkaisu on valmis.',
  'form.issn.publicationMedium.printed': 'Painettu',
  'form.issn.publicationMedium.electronical': 'Sähköinen',
  'form.issn.publicationMedium.online': 'Sähköinen',
  'form.issn.publicationMedium.cd_rom': 'CD-ROM',
  'form.issn.publicationMedium.cdrom': 'CD-ROM',
  'form.issn.publicationMedium.other': 'Muu',
  'form.issn.publicationCard.city': 'Kustannuspaikka',
  'form.issn.publicationCard.firstYear': 'Ilmestynyt alkaen (vuosi)',
  'form.issn.publicationCard.issued_from_number': 'Ilmestynyt alkaen (numero)',
  'form.issn.publicationCard.frequency': 'Ilmestymistiheys',
  'form.issn.publicationCard.other': 'muu, mikä?',
  'form.issn.publicationCard.publicationType': 'Julkaisutyyppi',
  'form.issn.publicationCard.publicationMedium': 'Julkaisumuoto',
  'form.issn.publicationCard.url': 'Julkaisun www-osoite',
  'form.issn.preview.publisherInfo': 'Julkaisijan tiedot',
  'form.issn.preview.name': 'Julkaisijan nimi',
  'form.issn.relatedPublications': 'Liittyvät julkaisut',
  'form.issn.preview.publicationDetails': 'Julkaisutiedot',
  'form.issn.preview.versions': 'Julkaisun versiot',

  // ISSN request
  'request.issn.preview.title': '{index}. Julkaisu - {title}',

  // TableComponent
  'table.rowsPerPage': 'Riviä sivulla',
  'table.total': 'Yhteensä',
  'table.forms': 'Lomakkeet',
  'table.formsOnOnePage': 'Lomakkeita',
  'table.headRows.active': 'Aktiivinen',
  'table.headRows.id': 'ID',
  'table.headRows.block': 'Lohko',
  'table.headRows.publicationType': 'Julkaisutyyppi',
  'table.headRows.identifier': 'Tunnus',

  // Publisher registry (Kustantajarekisteri)
  'publisherRegistry.title': 'Hae kustantajaa nimellä tai kustantajatunnuksella',
  'publisherRegistry.headRows.activeIdentifiers': 'Aktiiviset tunnukset',
  'publisherRegistry.publisher.otherNameForms': 'Muut nimimuodot',
  'publisherRegistry.publisher.previousNameForms': 'Aikaisemmat nimimuodot',
  'publisherRegistry.publisher.publisherHasQuitted': 'Kustantaja on lopettanut toimintansa',
  'publisherRegistry.publisher.noOtherNames': 'Ei muita nimimuotoja',
  'publisherRegistry.publisher.noPreviousNames': 'Ei aiempia nimiä',
  'publisherRegistry.publisher.typeOther': 'Muut kansityypit',
  'publisherRegistry.publisher.fileFormatOther': 'Muut tiedostomuodot',
  'publisherRegistry.publisher.manufacturer': 'Kirjapaino',
  'publisherRegistry.publisher.run': 'Painoksen suuruus',
  'publisherRegistry.publisher.edition': 'Painos',
  'publisherRegistry.publisher.role': 'Rooli',
  'publisherRegistry.popover.isbn': 'ISBN - Kirjat',
  'publisherRegistry.popover.ismn': 'ISMN - Nuottijulkaisut',

  // ISSN publication
  'publication.issn.title': 'Etsi ISSN-julkaisu nimikkeellä',
  'publication.issn.additionalDetails': 'Julkaisun lisätiedot',
  'publication.issn.manufacturer': 'Kirjapaino',
  'publication.issn.frequency': 'Ilmestymistiheys',
  'publication.issn.other': 'Jos muu, mikä?',
  'publication.issn.firstYear': 'Ilmestynyt alkaen (vuosi)',
  'publication.issn.issued_from_number': 'Ilmestynyt alkaen (numero)',
  'publication.issn.type': 'Julkaisutyyppi',
  'publication.issn.anotherFormat': 'Toinen julkaisumuoto',
  'publication.issn.mainSeries': 'Pääsarja',
  'publication.issn.subSeries': 'Alasarja',
  'publication.issn.previousNameForms': 'Aikaisemmat nimimuodot',
  'publication.issn.lastIssue': 'Viimeinen numero/vuosi',

  // Modals
  'modal.publicBatch.confirmation': 'Vahvistus / Bekräftelse / Confirmation',
  'modal.publicBatch.confirmation.text.part1': 'Vahvistan edustavani kustantajaa ',
  'modal.publicBatch.confirmation.text.part2': ' ja omistavani kustantajatunnuksen ',
  'modal.publicBatch.confirmation.text.part3': 'Jag bekräftar att jag representerar förlaget  ',
  'modal.publicBatch.confirmation.text.part4': ' och äger förlagsbeteckningen ',
  'modal.publicBatch.confirmation.text.part5': 'I confirm I represent ',
  'modal.publicBatch.confirmation.text.part6': ' (publisher ID {id})',

  // Service messages - used in action dispatchers (store/actions)
  'serviceMessage.registration.success': 'Lomake on lähetetty onnistuneesti.',
  'serviceMessage.registration.error': 'Lomakeen lähettäminen epäonnistui',
  'serviceMessage.requestCreate.successfull': 'Pyyntö lähetettiin onnistuneesti',
  'serviceMessage.requestCreate.unsuccessfull': 'Pyyntöä lähetettäessä tapahtui virhe',
  'serviceMessage.requestQuery.unsuccessfull': 'Pyyntöjen haku epäonnistui',
  'serviceMessage.requestRead.unsuccessfull': 'Pyynnön haku epäonnistui',
  'serviceMessage.publisherRead.unsuccessfull': 'Kustantajan haku epäonnistui',
  'serviceMessage.publisherSearch.unsuccessfull': 'Kustantajien haku epäonnistui',
  'serviceMessage.batchRead.unsuccessfull': 'Tunnuksen haku epäonnistui',
  'serviceMessage.batchQuery.unsuccessfull': 'Tunnuksien haku epäonnistui',
  'serviceMessage.batchDownload.successfull': 'Tunnuksien lataus onnistui',
  'serviceMessage.batchDownload.unsuccessfull': 'Tunnuksien lataus epäonnistui',

  // Service messages - errors
  'serviceMessage.turnstileScript.error': 'Tuntematon virhe. Ole hyvä ja yritä sivun latausta uudelleen.',

  // Turnstile info
  'form.turnstile.title': 'Tärkeä huomio',
  'form.turnstile.info': 'Siirtymällä täyttämään lomakkeen hyväksyt, että automaattista tunnistusta käytetään taustalla erottelemaan ihmiskäyttäjät robottikäyttäjistä. Automaattisen tunnistamisen yhteydessä tunnistamisen palveluntarjoaja (Cloudflare) saa tiedon IP-osoitteestasi.',
  'form.turnstile.info.batchdownload': 'Siirtymällä lataamaan tunnukset hyväksyt, että automaattista tunnistusta käytetään taustalla erottelemaan ihmiskäyttäjät robottikäyttäjistä. Automaattisen tunnistamisen yhteydessä tunnistamisen palveluntarjoaja (Cloudflare) saa tiedon IP-osoitteestasi.',
  'form.turnstile.link.privacy': 'Cloudflare tietosuojaseloste (englanniksi)',
  'form.turnstile.link.terms': 'Cloudflare käyttöehdot (englanniksi)'
};

export default fi;
